# Generated by Django 3.1 on 2020-12-11 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201106_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('counselor', 'Real Estate Counselor'), ('counselor_ie', 'Real Estate Counselor-IMPAKT ELITE'), ('managing_director', 'Managing Director'), ('assistent_manage', 'Assistent Manager'), ('secretariat', 'Secretariat'), ('it_administrator', 'IT Administrator'), ('specialist', 'Real Estate Specialist')], max_length=256, null=True),
        ),
    ]
