# Generated by Django 3.1 on 2020-12-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201216_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='position',
            field=models.IntegerField(default=100, verbose_name='Image Position'),
        ),
    ]
