# Generated by Django 3.1 on 2020-12-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201216_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='position',
            field=models.PositiveIntegerField(default=100, verbose_name='Image Position'),
        ),
    ]
