# Generated by Django 3.1 on 2020-12-17 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20201217_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_settings',
            new_name='layout_settings',
        ),
    ]
