# Generated by Django 3.1 on 2020-12-17 04:29

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20201217_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='layout_settings',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('darkMode', 'Dark Mode'), ('leftSidebarCondensed', 'Condensed Sidebar')], max_length=29, null=True, verbose_name='Layout Settings'),
        ),
    ]
