# Generated by Django 3.1 on 2020-12-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20201217_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('counselor', 'Real Estate Counselor'), ('counselor_ie', 'Real Estate Counselor-IMPAKT ELITE'), ('managing_director', 'Managing Director'), ('assistent_manage', 'Assistent Manager'), ('secretariat', 'Secretariat'), ('it_administrator', 'IT Administrator'), ('specialist', 'Real Estate Specialist')], max_length=256, null=True, verbose_name='Role'),
        ),
    ]
