# Generated by Django 3.1 on 2021-01-02 20:34

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20201219_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Last lame'),
        ),
        migrations.AlterField(
            model_name='user',
            name='layout_settings',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('darkMode', 'Dark mode'), ('leftSidebarCondensed', 'Condensed sidebar')], max_length=29, null=True, verbose_name='Layout settings'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('counselor', 'Real estate counselor'), ('counselor_ie', 'Real estate counselor-IMPAKT ELITE'), ('managing_director', 'Managing director'), ('assistent_manage', 'Assistent manager'), ('secretariat', 'Secretariat'), ('it_administrator', 'IT Administrator'), ('specialist', 'Real estate specialist')], max_length=256, null=True, verbose_name='Role'),
        ),
    ]
