# Generated by Django 3.1 on 2021-01-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210103_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='show_on_site',
            field=models.BooleanField(default=True, verbose_name='Show on site'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('counselor', 'Real estate counselor'), ('managing_director', 'Managing director'), ('assistant_manager', 'Assistant manager'), ('secretariat', 'Secretariat'), ('it_administrator', 'IT Administrator'), ('specialist', 'Real estate specialist')], max_length=256, null=True, verbose_name='Role'),
        ),
    ]
