# Generated by Django 3.1 on 2021-02-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userimage',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='userimage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
    ]
