# Generated by Django 3.1 on 2021-03-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20210216_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userimage',
            name='public',
        ),
    ]
