# Generated by Django 3.1 on 2021-03-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_userimage_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_on_site',
            field=models.BooleanField(default=True),
        ),
    ]
