# Generated by Django 3.1 on 2021-03-25 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20210321_2232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['position_on_site', 'email']},
        ),
    ]
