# Generated by Django 3.1 on 2021-11-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_title',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Roles'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('counselor', 'Real estate counselor'), ('managing_director', 'Managing director'), ('assistant_manager', 'Assistant manager'), ('secretariat', 'Secretariat'), ('it_administrator', 'IT Administrator'), ('specialist', 'Real estate specialist'), ('broker_owner', 'Broker owner')], max_length=256, null=True, verbose_name='Role'),
        ),
    ]
