# Generated by Django 3.1 on 2022-02-20 17:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_user_rex_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Web Agent URL'),
        ),
        migrations.AddField(
            model_name='user',
            name='external_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=50, null=True, verbose_name='Agent external ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='international_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='International ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_sale_associate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Specialization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rex_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=50, null=True, verbose_name='Rex User ID'),
        ),
    ]
