# Generated by Django 3.1 on 2022-02-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20220220_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rex_id',
        ),
    ]
