# Generated by Django 3.1 on 2022-02-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20220222_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='specialization',
            field=models.PositiveIntegerField(default=1310, verbose_name='Specialization'),
        ),
    ]
