# Generated by Django 3.1 on 2022-04-06 16:51

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20220316_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certificates',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('power_start', 'Power Start'), ('juridic', 'Juridic'), ('succed', 'Succed'), ('next_level', 'Next level in Real Estate'), ('you_and_remax', 'Tu și REMAX'), ('executive', 'Executive')], max_length=61, null=True, verbose_name='Certificates'),
        ),
    ]
