# Generated by Django 3.1 on 2022-04-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_user_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='User Description'),
        ),
    ]
