# Generated by Django 3.1 on 2022-05-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_user_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_999',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Token 999'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('counselor', 'Real estate counselor'), ('managing_director', 'Managing director'), ('assistant_manager', 'Assistant manager'), ('secretariat', 'Secretariat'), ('it_administrator', 'IT Administrator'), ('specialist', 'Real estate specialist'), ('broker_owner', 'Broker owner'), ('marketing_manager', 'Marketing Manager')], max_length=256, null=True, verbose_name='Role'),
        ),
    ]
