version: '3'

volumes:
  node_modules:
  dist:

services:
    db:
        image: postgres
        environment:
            - POSTGRES_USER=user
            - POSTGRES_DB=impakt
            - POSTGRES_PASSWORD=password
        ports:
            - "5432:5432"
        restart: unless-stopped

    web:
        build: .
        command: gunicorn crm.asgi:application --bind 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker --workers 2 --log-file=- --log-level debug
        environment:
            - DJANGO_SETTINGS_MODULE=crm.settings.remaxmd
            - ENVIRONMENT=development
            - CRM_API_KEY=Api-Key kj0dYAMZ.R7kZouO4Z636yGY7ZpAmIIwyQWgv7q6V
            - POSTGRES_DB_USER=user
            - POSTGRES_DB_NAME=impakt
            - POSTGRES_DB_PASSWORD=password
            - POSTGRES_DB_HOST=db
        env_file:
            - .env
        volumes:
            - .:/app
            - node_modules:/app/ui/static/node_modules
            - dist:/app/ui/static
        ports:
            - "8000:8000"
        depends_on:
            - db
        restart: unless-stopped

    rmx-redis-queue:
        container_name: rmx-redis-queue
        image: redis:latest
        platform: linux/amd64
        ports:
            - "6379:6379"

    rmx-rq-worker:
        container_name: rmx-rq-worker
        build: .
        command: ./manage.py rqworker
        environment:
            - DJANGO_SETTINGS_MODULE=crm.settings.remaxmd
            - ENVIRONMENT=development
            - CRM_API_KEY=Api-Key kj0dYAMZ.R7kZouO4Z636yGY7ZpAmIIwyQWgv7q6V
            - POSTGRES_DB_USER=user
            - POSTGRES_DB_NAME=impakt
            - POSTGRES_DB_PASSWORD=password
            - POSTGRES_DB_HOST=db
        env_file:
            - .env
        volumes:
            - .:/app
            - node_modules:/app/ui/static/node_modules
            - dist:/app/ui/static
        depends_on:
            - db
            - rmx-redis-queue
        restart: unless-stopped