# Generated by Django 3.1 on 2020-10-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('med', 'Med'), ('high', 'High')], default='low', max_length=20),
            preserve_default=False,
        ),
    ]
