# Generated by Django 3.1 on 2020-10-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='to_do', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('med', 'Med'), ('high', 'High')], max_length=20, null=True),
        ),
    ]
