# Generated by Django 3.1 on 2020-10-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20201028_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20, null=True),
        ),
    ]
