# Generated by Django 3.1 on 2020-12-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_activity_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='hyperlink',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
