# Generated by Django 3.1 on 2020-12-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0010_activity_hyperlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
