# Generated by Django 3.1 on 2020-12-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0012_auto_20201219_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_allocated',
            field=models.BooleanField(default=False, verbose_name='Allocate'),
        ),
    ]
