# Generated by Django 3.1 on 2020-12-22 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0013_activity_is_allocated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='is_allocated',
            new_name='is_available',
        ),
    ]
