# Generated by Django 3.1 on 2020-12-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0014_auto_20201222_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_taken',
            field=models.BooleanField(default=False, verbose_name='Taken'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='Available'),
        ),
    ]
