# Generated by Django 3.1 on 2020-12-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0015_auto_20201222_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('sale', 'Sale Offers'), ('rent', 'Rent Offers'), ('done', 'Done')], default='sale', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
