# Generated by Django 3.1 on 2020-12-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0016_auto_20201223_0317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='demand',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='status',
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_status',
            field=models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='', max_length=256, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='activity',
            name='lead_status',
            field=models.CharField(choices=[('sale', 'Sale Offers'), ('rent', 'Rent Offers'), ('done', 'Done')], default='', max_length=256, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='activity',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('viewing', 'Viewing'), ('virtual_viewing', 'Virtual Viewing'), ('demand_activity', 'Demand Activity'), ('property_lead_generation', 'Property Lead Generation'), ('client_lead_generation', 'Client Lead Generation'), ('telephone_conversation', 'Telephone Conversation'), ('photo_viewing', 'Photo Viewing')], default='viewing', max_length=256, null=True, verbose_name='Type'),
        ),
    ]
