# Generated by Django 3.1 on 2020-12-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0018_auto_20201228_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_lead',
            field=models.BooleanField(default=False, verbose_name='Is Lead'),
        ),
    ]
