# Generated by Django 3.1 on 2020-12-28 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_auto_20201216_1626'),
        ('properties', '0062_auto_20201219_1405'),
        ('demands', '0021_auto_20201208_1628'),
        ('activities', '0019_activity_is_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_status',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='lead_status',
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('sale', 'Sale Offers'), ('rent', 'Rent Offers'), ('processed', 'Processed')], default='', max_length=256, null=True, verbose_name='Lead Status'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='demand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demands.demand', verbose_name='Demand'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='hyperlink',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property', verbose_name='Property'),
        ),
    ]
