# Generated by Django 3.1 on 2020-12-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0021_auto_20201229_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='is_lead',
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(blank=True, choices=[('viewing', 'Viewing'), ('virtual_viewing', 'Virtual Viewing'), ('demand_activity', 'Demand Activity'), ('property_lead_generation', 'Property Lead Generation'), ('client_lead_generation', 'Client Lead Generation'), ('telephone_conversation', 'Telephone Conversation'), ('photo_viewing', 'Photo Viewing')], default='', max_length=256, verbose_name='Type'),
        ),
    ]
