# Generated by Django 3.1 on 2020-12-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0024_auto_20201229_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(blank=True, choices=[('viewing', 'Viewing'), ('virtual_viewing', 'Virtual Viewing'), ('demand_lead_generation', 'Demand Lead Generation'), ('property_lead_generation', 'Property Lead Generation'), ('client_lead_generation', 'Client Lead Generation'), ('telephone_conversation', 'Telephone Conversation'), ('photo_viewing', 'Photo Viewing')], default='', max_length=256, verbose_name='Type'),
        ),
    ]
