# Generated by Django 3.1 on 2021-01-02 15:18

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0025_auto_20201230_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='linked_with',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('studio', 'Studio'), ('commercial', 'Commercial space'), ('land', 'Land')], max_length=56, null=True, verbose_name='Linked with'),
        ),
    ]
