# Generated by Django 3.1 on 2021-01-02 20:34

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0026_activity_linked_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due date'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='linked_with',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('property', 'Property'), ('demand', 'Demand'), ('client', 'Client')], max_length=56, null=True, verbose_name='Linked with'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('to_do', 'To do'), ('in_progress', 'In progress'), ('done', 'Done'), ('sale', 'Sale leads'), ('rent', 'Rent leads'), ('processed', 'Processed')], default='', max_length=256, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(blank=True, choices=[('viewing', 'Viewing'), ('virtual_viewing', 'Virtual viewing'), ('demand_lead_generation', 'Demand lead generation'), ('property_lead_generation', 'Property lead generation'), ('client_lead_generation', 'Client lead generation'), ('telephone_conversation', 'Telephone conversation'), ('photo_viewing', 'Photo Viewing')], default='', max_length=256, verbose_name='Type'),
        ),
    ]
