# Generated by Django 3.1 on 2021-01-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0027_auto_20210102_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(blank=True, default='No title', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(blank=True, choices=[('viewing', 'Viewing'), ('virtual_viewing', 'Virtual viewing'), ('demand_lead_generation', 'Demand lead generation'), ('property_lead_generation', 'Property lead generation'), ('client_lead_generation', 'Client lead generation'), ('telephone_conversation', 'Telephone conversation'), ('photo_viewing', 'Photo viewing')], default='', max_length=256, verbose_name='Type'),
        ),
    ]
