# Generated by Django 3.1 on 2021-01-28 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0028_auto_20210103_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archive'),
        ),
    ]
