# Generated by Django 3.1 on 2021-03-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0030_auto_20210214_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Archive'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('to_do', 'To do'), ('in_progress', 'In progress'), ('done', 'Done'), ('sale', 'Sale leads'), ('rent', 'Rent leads'), ('processed', 'Processed')], db_index=True, default='', max_length=256, null=True, verbose_name='Status'),
        ),
    ]
