# Generated by Django 3.1 on 2021-03-23 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0031_auto_20210323_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at']},
        ),
    ]
