# Generated by Django 3.1 on 2020-09-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200914_0637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='email_home',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='phone_home',
            new_name='phone_1',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='phone_work',
            new_name='phone_2',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email_work',
        ),
        migrations.AddField(
            model_name='client',
            name='phone_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
