# Generated by Django 3.1 on 2020-09-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20200914_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
