# Generated by Django 3.1 on 2020-09-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_1',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
