# Generated by Django 3.1 on 2020-11-06 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offices', '0004_auto_20201106_1534'),
        ('clients', '0010_auto_20201029_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='client',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='client',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='client',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='offices.office', verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_1',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Phone 1'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone 2'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone 3'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Agent'),
        ),
    ]
