# Generated by Django 3.1 on 2020-12-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_auto_20201123_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Last Name'),
        ),
    ]
