# Generated by Django 3.1 on 2021-01-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_auto_20210113_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Is private'),
        ),
    ]
