# Generated by Django 3.1 on 2021-01-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_client_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_1',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Phone 1'),
        ),
    ]
