# Generated by Django 3.1 on 2021-01-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_auto_20210128_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='VIP'),
        ),
    ]
