# Generated by Django 3.1 on 2021-02-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_auto_20210129_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Deleted'),
        ),
    ]
