# Generated by Django 3.1 on 2021-04-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_auto_20210325_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='national_id',
            field=models.CharField(blank=True, max_length=56, null=True, verbose_name='National ID'),
        ),
    ]
