# Generated by Django 3.1 on 2022-02-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0027_auto_20211228_1736'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set(),
        ),
    ]
