# Generated by Django 3.1 on 2020-09-23 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_delete_location'),
        ('demands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='location',
        ),
        migrations.AddField(
            model_name='demand',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city', verbose_name='Localitate'),
        ),
        migrations.AddField(
            model_name='demand',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.region', verbose_name='Județ'),
        ),
        migrations.AddField(
            model_name='demand',
            name='zones',
            field=models.ManyToManyField(blank=True, to='locations.Zone', verbose_name='Zonă'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='price_max',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='price_min',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='surface_max',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='surface_min',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
