# Generated by Django 3.1 on 2020-09-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0002_auto_20200923_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='rooms_max',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='rooms_min',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True),
        ),
    ]
