# Generated by Django 3.1 on 2020-09-24 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0002_auto_20200923_1142'),
        ('demands', '0004_auto_20200923_1554'),
    ]

    operations = [
    ]
