# Generated by Django 3.1 on 2020-09-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_delete_multiplezoneslocation'),
        ('demands', '0005_merge_20200924_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='region',
        ),
        migrations.AddField(
            model_name='demand',
            name='region',
            field=models.ManyToManyField(blank=True, to='locations.Region', verbose_name='Județ'),
        ),
    ]
