# Generated by Django 3.1 on 2020-09-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0009_auto_20200925_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='comments',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='contract_number',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='contract_type',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='price_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='price_min',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='surface_max',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='surface_min',
            field=models.FloatField(null=True),
        ),
    ]
