# Generated by Django 3.1 on 2020-09-28 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_auto_20200928_0855'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0007_auto_20200928_0855'),
        ('demands', '0010_auto_20200925_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='attic_excluded',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demands', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='comments',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='contract_number',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='contract_type',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='ground_floor_excluded',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='limit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='new_building',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demands', to='offices.office'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='price_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='price_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='property_type',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('studio', 'Studio'), ('commercial', 'Commercial space'), ('land', 'Land')], max_length=56),
        ),
        migrations.AlterField(
            model_name='demand',
            name='rooms_max',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='rooms_min',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='surface_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='surface_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='top_floor_excluded',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='type',
            field=models.CharField(blank=True, choices=[('sale', 'Sale'), ('rent', 'Rent')], max_length=56),
        ),
        migrations.AlterField(
            model_name='demand',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demands', to=settings.AUTH_USER_MODEL),
        ),
    ]
