# Generated by Django 3.1 on 2020-10-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0011_auto_20200928_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
