# Generated by Django 3.1 on 2020-10-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0012_auto_20201007_1508'),
    ]

    operations = [
    ]
