# Generated by Django 3.1 on 2020-10-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0014_auto_20201021_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demand',
            name='garage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demand',
            name='key_possession',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demand',
            name='parking_spot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demand',
            name='pet_friendly',
            field=models.BooleanField(default=False),
        ),
    ]
