# Generated by Django 3.1 on 2020-11-04 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_auto_20201104_2207'),
        ('demands', '0016_remove_demand_key_possession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='type',
            field=models.CharField(blank=True, choices=[('sale', 'Sale'), ('rent', 'Rent')], max_length=56, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='zones',
            field=models.ManyToManyField(blank=True, to='locations.Zone', verbose_name='Zone'),
        ),
    ]
