# Generated by Django 3.1 on 2020-11-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_auto_20201104_2207'),
        ('demands', '0018_auto_20201106_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='zones',
            field=models.ManyToManyField(blank=True, to='locations.Zone', verbose_name='Zones'),
        ),
    ]
