# Generated by Django 3.1 on 2020-11-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0019_auto_20201116_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='limit_date',
            field=models.DateField(blank=True, null=True, verbose_name='Limit Date'),
        ),
    ]
