# Generated by Django 3.1 on 2020-12-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0020_auto_20201124_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='rooms_max',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='Rooms Max'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='rooms_min',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='Rooms Min'),
        ),
    ]
