# Generated by Django 3.1 on 2021-01-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0063_auto_20210102_2034'),
        ('demands', '0021_auto_20201208_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='furnished',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='garage',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='ground_floor_excluded',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='mansard_excluded',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='new_construction',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='parking_spot',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='pet_friendly',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='top_floor_excluded',
        ),
        migrations.AddField(
            model_name='demand',
            name='features',
            field=models.ManyToManyField(blank=True, to='properties.Feature', verbose_name='Features'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='property_type',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('studio', 'Studio'), ('commercial', 'Commercial space'), ('land', 'Land')], max_length=56, verbose_name='Property type'),
        ),
    ]
