# Generated by Django 3.1 on 2021-01-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_auto_20201104_2207'),
        ('demands', '0022_auto_20210102_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='zones',
            field=models.ManyToManyField(blank=True, null=True, to='locations.Zone', verbose_name='Zones'),
        ),
    ]
