# Generated by Django 3.1 on 2021-01-02 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_auto_20201104_2207'),
        ('demands', '0023_auto_20210102_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='ground_floor_excluded',
            field=models.BooleanField(default=False, verbose_name='Ground Floor Excluded'),
        ),
        migrations.AddField(
            model_name='demand',
            name='mansard_excluded',
            field=models.BooleanField(default=False, verbose_name='Mansard excluded'),
        ),
        migrations.AddField(
            model_name='demand',
            name='top_floor_excluded',
            field=models.BooleanField(default=False, verbose_name='Top Floor Excluded'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='zones',
            field=models.ManyToManyField(blank=True, to='locations.Zone', verbose_name='Zones'),
        ),
    ]
