# Generated by Django 3.1 on 2021-01-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0024_auto_20210102_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='rooms_max',
        ),
        migrations.RemoveField(
            model_name='demand',
            name='rooms_min',
        ),
        migrations.AddField(
            model_name='demand',
            name='rooms',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '+4')], null=True, verbose_name='Rooms'),
        ),
    ]
