# Generated by Django 3.1 on 2021-01-28 19:35

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0025_auto_20210103_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='in_development',
            field=models.BooleanField(default=False, verbose_name='In development'),
        ),
        migrations.AddField(
            model_name='demand',
            name='new_building',
            field=models.BooleanField(default=False, verbose_name='New building'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('sale', 'Sale'), ('exclusive_sale', 'Exclusive sale'), ('rent', 'Rent'), ('exclusive_rent', 'Exclusive rent')], max_length=70, null=True, verbose_name='Contract Type'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='rooms',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4 +')], max_length=50, null=True, verbose_name='Rooms'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='type',
            field=models.CharField(blank=True, choices=[('sale', 'Sale'), ('rent', 'Rent')], max_length=56, verbose_name='Transaction type'),
        ),
    ]
