# Generated by Django 3.1 on 2021-01-29 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0026_auto_20210128_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='contract_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Contract date'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='contract_number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)], verbose_name='Contract number'),
        ),
    ]
