# Generated by Django 3.1 on 2021-01-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0027_auto_20210129_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demand',
            name='contract_date',
        ),
        migrations.AddField(
            model_name='demand',
            name='contract_signing_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Contract signing date'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('buy', 'Buy'), ('rent', 'Rent')], max_length=70, null=True, verbose_name='Contract Type'),
        ),
    ]
