# Generated by Django 3.1 on 2021-03-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0032_auto_20210214_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='property_subtype',
            field=models.CharField(blank=True, choices=[('detached', 'Detached house'), ('terraced', 'Terraced house'), ('attached', 'Attached house'), ('block_apartment', 'Block apartment'), ('villa_apartment', 'Villa apartment'), ('studio_apartment', 'Studio apartment'), ('commercial_space', 'Commercial space'), ('office_space', 'Office space'), ('industrial_space', 'Industrial space'), ('agricultural_land', 'Agricultural land'), ('construction_land', 'construction_land'), ('cabin', 'cabin'), ('hotel', 'Hotel'), ('guest_house', 'Guest house')], max_length=56, verbose_name='Property type'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='property_type',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('studio', 'Studio'), ('commercial', 'Commercial space'), ('land', 'Land'), ('hotel', 'Hotel'), ('cabin', 'Cabin')], max_length=56, verbose_name='Property type'),
        ),
    ]
