# Generated by Django 3.1 on 2021-03-21 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0035_demand_key_holding'),
        ('demands', '0033_auto_20210321_1848'),
    ]

    operations = [
    ]
