# Generated by Django 3.1 on 2021-03-21 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0036_merge_20210321_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='property_subtype',
            field=models.CharField(blank=True, choices=[('detached', 'Detached house'), ('terraced', 'Terraced house'), ('attached', 'Attached house'), ('block_apartment', 'Block apartment'), ('villa_apartment', 'Villa apartment'), ('studio_apartment', 'Studio apartment'), ('commercial_space', 'Commercial space'), ('office_space', 'Office space'), ('industrial_space', 'Industrial space'), ('agricultural_land', 'Agricultural land'), ('construction_land', 'Construction land'), ('cabin', 'Cabin'), ('hotel', 'Hotel'), ('guest_house', 'Guest house')], max_length=56, verbose_name='Property type'),
        ),
    ]
