# Generated by Django 3.1 on 2021-03-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0037_auto_20210321_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='contract_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Contract number'),
        ),
    ]
