# Generated by Django 3.1 on 2021-04-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0040_demand_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='contract_register_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Contract register'),
        ),
        migrations.AddField(
            model_name='demand',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Contract signing date'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='status',
            field=models.CharField(blank=True, choices=[('prospect', 'Prospect'), ('contracted', 'Contracted'), ('transacted', 'Request transacted by Impakt'), ('transacted_by_others', 'Request transacted by others'), ('transacted_by_owner', 'Request transacted by owner'), ('withdrawn', 'Request withdrawn')], default='prospect', max_length=50, null=True, verbose_name='Status'),
        ),
    ]
