# Generated by Django 3.1 on 2021-04-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0041_auto_20210401_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='type',
            field=models.CharField(blank=True, choices=[('sale', 'Buy'), ('rent', 'Rent')], max_length=56, verbose_name='Transaction type'),
        ),
    ]
