# Generated by Django 3.1 on 2021-04-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0042_auto_20210401_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='property_subtype',
            field=models.CharField(blank=True, choices=[('detached', 'Detached house'), ('terraced', 'Terraced house'), ('attached', 'Attached house'), ('block_apartment', 'Block apartment'), ('villa_apartment', 'Villa apartment'), ('studio_apartment', 'Studio apartment'), ('commercial_space', 'Commercial space'), ('office_space', 'Office space'), ('industrial_space', 'Industrial space'), ('agricultural_land', 'Agricultural land'), ('construction_land', 'Construction land'), ('cabin', 'Cabin'), ('hotel', 'Hotel'), ('guest_house', 'Guest house')], max_length=56, verbose_name='Property subtype'),
        ),
        migrations.AlterField(
            model_name='demand',
            name='status',
            field=models.CharField(blank=True, choices=[('prospect', 'Prospect'), ('contracted', 'Contracted'), ('transacted', 'Request transacted by us'), ('transacted_by_others', 'Request transacted by others'), ('transacted_by_owner', 'Request transacted by owner'), ('withdrawn', 'Request withdrawn')], default='prospect', max_length=50, null=True, verbose_name='Status'),
        ),
    ]
