# Generated by Django 3.1 on 2021-07-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0094_propertydocument'),
        ('demands', '0043_auto_20210403_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='offers_of_interest',
            field=models.ManyToManyField(blank=True, to='properties.Property', verbose_name='Offers of interest'),
        ),
    ]
