# Generated by Django 3.1 on 2022-01-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0044_demand_offers_of_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='property_type',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('studio', 'Studio'), ('commercial', 'Commercial space'), ('land', 'Land'), ('hotel', 'Hotel'), ('cabin', 'Cabin'), ('basement_parking', 'Basement Parking'), ('garage', 'Garage'), ('storage_room', 'Storage Room')], max_length=56, verbose_name='Property type'),
        ),
    ]
