# Generated by Django 3.1 on 2022-01-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0045_auto_20220111_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='property_subtype',
            field=models.CharField(blank=True, choices=[('detached', 'Detached house'), ('terraced', 'Terraced house'), ('attached', 'Attached house'), ('block_apartment', 'Block apartment'), ('villa_apartment', 'Villa apartment'), ('studio_apartment', 'Studio apartment'), ('commercial_space', 'Commercial space'), ('office_space', 'Office space'), ('industrial_space', 'Industrial space'), ('agricultural_land', 'Agricultural land'), ('construction_land', 'Construction land'), ('cabin', 'Cabin'), ('hotel', 'Hotel'), ('guest_house', 'Guest house'), ('garage', 'Garage'), ('basement_parking', 'Basement Parking'), ('storage_room', 'Storage Room')], max_length=56, verbose_name='Property subtype'),
        ),
    ]
