# Generated by Django 3.1 on 2022-10-11 14:44

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0048_auto_20220121_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='commission',
            field=models.IntegerField(blank=True, null=True, verbose_name='Commission Seller'),
        ),
        migrations.AddField(
            model_name='demand',
            name='commission_buyer',
            field=models.IntegerField(blank=True, null=True, verbose_name='Commission Buyer'),
        ),
        migrations.AddField(
            model_name='demand',
            name='commission_buyer_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Commission Buyer %'),
        ),
        migrations.AddField(
            model_name='demand',
            name='commission_colaboration',
            field=models.FloatField(blank=True, null=True, verbose_name='Commission for colaboration'),
        ),
        migrations.AddField(
            model_name='demand',
            name='commission_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Commission Seller %'),
        ),
        migrations.AddField(
            model_name='demand',
            name='commission_success',
            field=models.FloatField(blank=True, null=True, verbose_name='Commission for successful transaction'),
        ),
        migrations.AddField(
            model_name='demand',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='demand',
            name='final_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Final price'),
        ),
    ]
