# Generated by Django 3.1 on 2020-08-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('content_type', 'object_id')},
        ),
    ]
