# Generated by Django 3.1 on 2020-08-11 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offices', '0002_office_deleted'),
        ('properties', '0003_auto_20200811_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='object_id',
            new_name='attributes_object_id',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='content_type',
            new_name='attributes_type',
        ),
        migrations.AddField(
            model_name='property',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.CharField(blank=True, max_length=2500),
        ),
        migrations.AddField(
            model_name='property',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='offices.office'),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('active', 'Active'), ('transacted', 'Transacted'), ('withdrawn', 'Withdrawn')], default='incomplete', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='title',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('attributes_type', 'attributes_object_id')},
        ),
    ]
