# Generated by Django 3.1 on 2020-08-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('clients', '0001_initial'),
        ('properties', '0004_auto_20200811_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('description_private', models.TextField(blank=True, max_length=3000)),
                ('description_sentimental', models.TextField(blank=True, max_length=3000)),
                ('surface_total', models.IntegerField(null=True)),
                ('surface_util', models.IntegerField(null=True)),
                ('surface_built', models.IntegerField(null=True)),
                ('surface_field', models.IntegerField(null=True)),
                ('front_line', models.IntegerField(null=True)),
                ('partitioning', models.CharField(choices=[('open-space', 'Open-space'), ('circuit', 'Circuit'), ('semidetached', 'Semi-detached'), ('detached', 'Detached')], max_length=50, null=True)),
                ('comfort', models.CharField(choices=[('incomplete', 'Incomplete'), ('active', 'Active'), ('transacted', 'Transacted'), ('withdrawn', 'Withdrawn')], max_length=50, null=True)),
                ('orientation', models.CharField(choices=[('north', 'North'), ('northeast', 'Northeast'), ('east', 'East'), ('southeast', 'Southeast'), ('south', 'South'), ('southwest', 'Southwest'), ('west', 'West'), ('northwest', 'Northwest')], max_length=50, null=True)),
                ('construction_year', models.IntegerField(null=True)),
                ('new_construction', models.BooleanField(default=False)),
                ('interior_state', models.CharField(choices=[('classic', 'Classic'), ('semi-finished', 'Semi-finished'), ('finished', 'Finished'), ('unfinished', 'Unfinished'), ('lux', 'Lux')], max_length=50, null=True)),
                ('construction_material', models.CharField(choices=[('brick', 'Brick'), ('concrete', 'Concrete'), ('bca', 'BCA'), ('wood', 'Wood')], max_length=50, null=True)),
                ('rooms_number', models.IntegerField(null=True)),
                ('bathrooms_number', models.IntegerField(null=True)),
                ('kitchens_number', models.IntegerField(null=True)),
                ('balconies_number', models.IntegerField(null=True)),
                ('floors', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('description_private', models.TextField(blank=True, max_length=3000)),
                ('description_sentimental', models.TextField(blank=True, max_length=3000)),
                ('surface_total', models.IntegerField(null=True)),
                ('surface_util', models.IntegerField(null=True)),
                ('surface_built', models.IntegerField(null=True)),
                ('surface_field', models.IntegerField(null=True)),
                ('front_line', models.IntegerField(null=True)),
                ('partitioning', models.CharField(choices=[('open-space', 'Open-space'), ('circuit', 'Circuit'), ('semidetached', 'Semi-detached'), ('detached', 'Detached')], max_length=50, null=True)),
                ('comfort', models.CharField(choices=[('incomplete', 'Incomplete'), ('active', 'Active'), ('transacted', 'Transacted'), ('withdrawn', 'Withdrawn')], max_length=50, null=True)),
                ('orientation', models.CharField(choices=[('north', 'North'), ('northeast', 'Northeast'), ('east', 'East'), ('southeast', 'Southeast'), ('south', 'South'), ('southwest', 'Southwest'), ('west', 'West'), ('northwest', 'Northwest')], max_length=50, null=True)),
                ('construction_year', models.IntegerField(null=True)),
                ('new_construction', models.BooleanField(default=False)),
                ('interior_state', models.CharField(choices=[('classic', 'Classic'), ('semi-finished', 'Semi-finished'), ('finished', 'Finished'), ('unfinished', 'Unfinished'), ('lux', 'Lux')], max_length=50, null=True)),
                ('construction_material', models.CharField(choices=[('brick', 'Brick'), ('concrete', 'Concrete'), ('bca', 'BCA'), ('wood', 'Wood')], max_length=50, null=True)),
                ('rooms_number', models.IntegerField(null=True)),
                ('bathrooms_number', models.IntegerField(null=True)),
                ('kitchens_number', models.IntegerField(null=True)),
                ('balconies_number', models.IntegerField(null=True)),
                ('floors', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudioAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('description_private', models.TextField(blank=True, max_length=3000)),
                ('description_sentimental', models.TextField(blank=True, max_length=3000)),
                ('surface_total', models.IntegerField(null=True)),
                ('surface_util', models.IntegerField(null=True)),
                ('surface_built', models.IntegerField(null=True)),
                ('surface_field', models.IntegerField(null=True)),
                ('front_line', models.IntegerField(null=True)),
                ('partitioning', models.CharField(choices=[('open-space', 'Open-space'), ('circuit', 'Circuit'), ('semidetached', 'Semi-detached'), ('detached', 'Detached')], max_length=50, null=True)),
                ('comfort', models.CharField(choices=[('incomplete', 'Incomplete'), ('active', 'Active'), ('transacted', 'Transacted'), ('withdrawn', 'Withdrawn')], max_length=50, null=True)),
                ('orientation', models.CharField(choices=[('north', 'North'), ('northeast', 'Northeast'), ('east', 'East'), ('southeast', 'Southeast'), ('south', 'South'), ('southwest', 'Southwest'), ('west', 'West'), ('northwest', 'Northwest')], max_length=50, null=True)),
                ('construction_year', models.IntegerField(null=True)),
                ('new_construction', models.BooleanField(default=False)),
                ('interior_state', models.CharField(choices=[('classic', 'Classic'), ('semi-finished', 'Semi-finished'), ('finished', 'Finished'), ('unfinished', 'Unfinished'), ('lux', 'Lux')], max_length=50, null=True)),
                ('construction_material', models.CharField(choices=[('brick', 'Brick'), ('concrete', 'Concrete'), ('bca', 'BCA'), ('wood', 'Wood')], max_length=50, null=True)),
                ('rooms_number', models.IntegerField(null=True)),
                ('bathrooms_number', models.IntegerField(null=True)),
                ('kitchens_number', models.IntegerField(null=True)),
                ('balconies_number', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='apartmentattributes',
            name='is_big',
        ),
        migrations.RemoveField(
            model_name='landattributes',
            name='is_free',
        ),
        migrations.RemoveField(
            model_name='property',
            name='description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='title',
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='balconies_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='bathrooms_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='comfort',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('active', 'Active'), ('transacted', 'Transacted'), ('withdrawn', 'Withdrawn')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='construction_material',
            field=models.CharField(choices=[('brick', 'Brick'), ('concrete', 'Concrete'), ('bca', 'BCA'), ('wood', 'Wood')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='construction_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='description',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='description_private',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='description_sentimental',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='front_line',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='interior_state',
            field=models.CharField(choices=[('classic', 'Classic'), ('semi-finished', 'Semi-finished'), ('finished', 'Finished'), ('unfinished', 'Unfinished'), ('lux', 'Lux')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='kitchens_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='new_construction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='orientation',
            field=models.CharField(choices=[('north', 'North'), ('northeast', 'Northeast'), ('east', 'East'), ('southeast', 'Southeast'), ('south', 'South'), ('southwest', 'Southwest'), ('west', 'West'), ('northwest', 'Northwest')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='partitioning',
            field=models.CharField(choices=[('open-space', 'Open-space'), ('circuit', 'Circuit'), ('semidetached', 'Semi-detached'), ('detached', 'Detached')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='rooms_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='surface_built',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='surface_field',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='surface_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='surface_util',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='title',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='landattributes',
            name='description',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='landattributes',
            name='description_private',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='landattributes',
            name='description_sentimental',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='landattributes',
            name='front_line',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='landattributes',
            name='surface_built',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='landattributes',
            name='surface_field',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='landattributes',
            name='surface_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='landattributes',
            name='surface_util',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='landattributes',
            name='title',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='property',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='clients.client'),
        ),
        migrations.AddField(
            model_name='property',
            name='contract_number',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='property',
            name='contract_type',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='property',
            name='exclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location'),
        ),
        migrations.AddField(
            model_name='property',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price_minimum',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price_per_sqm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='promote_site',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='promote_site_homepage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='promoted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='special_offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='featuregroup',
            name='property_types',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('studio', 'Studio'), ('commercial', 'Commercial space'), ('land', 'Land')], max_length=56),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('studio', 'Studio'), ('commercial', 'Commercial space'), ('land', 'Land')], max_length=56),
        ),
    ]
