# Generated by Django 3.1 on 2020-09-14 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_auto_20200913_1837'),
        ('properties', '0007_auto_20200914_0543'),
    ]

    operations = [
    ]
