# Generated by Django 3.1 on 2020-09-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_merge_20200914_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('studio', 'Studio'), ('commercial', 'Commercial space'), ('land', 'Land')], max_length=56),
        ),
    ]
