# Generated by Django 3.1 on 2020-09-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_auto_20200914_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='attributes_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
