# Generated by Django 3.1 on 2020-09-15 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('properties', '0010_auto_20200915_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='attributes_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
