# Generated by Django 3.1 on 2020-09-15 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_auto_20200915_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featuregroup',
            old_name='property_types',
            new_name='property_type',
        ),
    ]
