# Generated by Django 3.1 on 2020-09-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_auto_20200915_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='deleted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
