# Generated by Django 3.1 on 2020-09-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_property_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
