# Generated by Django 3.1 on 2020-09-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_auto_20200915_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
    ]
