# Generated by Django 3.1 on 2020-09-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_auto_20200917_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='contract_number',
            field=models.CharField(default=None, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='contract_type',
            field=models.CharField(default=None, max_length=70, null=True),
        ),
    ]
