# Generated by Django 3.1 on 2020-09-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_auto_20200917_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='contract_number',
            field=models.CharField(blank=True, default=0, max_length=70),
        ),
        migrations.AlterField(
            model_name='property',
            name='contract_type',
            field=models.CharField(blank=True, default=0, max_length=70),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_minimum',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_sqm',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
