# Generated by Django 3.1 on 2020-09-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_auto_20200917_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='contract_number',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='property',
            name='contract_type',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_minimum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_sqm',
            field=models.IntegerField(null=True),
        ),
    ]
