# Generated by Django 3.1 on 2020-09-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_auto_20200922_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_minimum',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price_per_sqm',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('studio', 'Studio'), ('commercial', 'Commercial space'), ('land', 'Land')], max_length=56, null=True),
        ),
    ]
