# Generated by Django 3.1 on 2020-09-28 07:05

from django.db import migrations, models
import django.db.models.deletion
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_auto_20200925_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(max_length=255, upload_to=properties.models.image_upload_path)),
                ('public', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
        ),
    ]
