# Generated by Django 3.1 on 2020-09-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_propertyimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentattributes',
            name='balconies_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='bathrooms_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='comfort',
            field=models.CharField(blank=True, choices=[('incomplete', 'Incomplete'), ('active', 'Active'), ('transacted', 'Transacted'), ('withdrawn', 'Withdrawn')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='construction_material',
            field=models.CharField(blank=True, choices=[('brick', 'Brick'), ('concrete', 'Concrete'), ('bca', 'BCA'), ('wood', 'Wood')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='construction_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='front_line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='interior_state',
            field=models.CharField(blank=True, choices=[('classic', 'Classic'), ('semi-finished', 'Semi-finished'), ('finished', 'Finished'), ('unfinished', 'Unfinished'), ('lux', 'Lux')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='kitchens_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='new_construction',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='orientation',
            field=models.CharField(blank=True, choices=[('north', 'North'), ('northeast', 'Northeast'), ('east', 'East'), ('southeast', 'Southeast'), ('south', 'South'), ('southwest', 'Southwest'), ('west', 'West'), ('northwest', 'Northwest')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='partitioning',
            field=models.CharField(blank=True, choices=[('open-space', 'Open-space'), ('circuit', 'Circuit'), ('semidetached', 'Semi-detached'), ('detached', 'Detached')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='rooms_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_field',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_util',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='balconies_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='bathrooms_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='comfort',
            field=models.CharField(blank=True, choices=[('incomplete', 'Incomplete'), ('active', 'Active'), ('transacted', 'Transacted'), ('withdrawn', 'Withdrawn')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='construction_material',
            field=models.CharField(blank=True, choices=[('brick', 'Brick'), ('concrete', 'Concrete'), ('bca', 'BCA'), ('wood', 'Wood')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='construction_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='front_line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='interior_state',
            field=models.CharField(blank=True, choices=[('classic', 'Classic'), ('semi-finished', 'Semi-finished'), ('finished', 'Finished'), ('unfinished', 'Unfinished'), ('lux', 'Lux')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='kitchens_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='new_construction',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='orientation',
            field=models.CharField(blank=True, choices=[('north', 'North'), ('northeast', 'Northeast'), ('east', 'East'), ('southeast', 'Southeast'), ('south', 'South'), ('southwest', 'Southwest'), ('west', 'West'), ('northwest', 'Northwest')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='partitioning',
            field=models.CharField(blank=True, choices=[('open-space', 'Open-space'), ('circuit', 'Circuit'), ('semidetached', 'Semi-detached'), ('detached', 'Detached')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='rooms_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_field',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_util',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='balconies_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='bathrooms_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='comfort',
            field=models.CharField(blank=True, choices=[('incomplete', 'Incomplete'), ('active', 'Active'), ('transacted', 'Transacted'), ('withdrawn', 'Withdrawn')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='construction_material',
            field=models.CharField(blank=True, choices=[('brick', 'Brick'), ('concrete', 'Concrete'), ('bca', 'BCA'), ('wood', 'Wood')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='construction_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='front_line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='interior_state',
            field=models.CharField(blank=True, choices=[('classic', 'Classic'), ('semi-finished', 'Semi-finished'), ('finished', 'Finished'), ('unfinished', 'Unfinished'), ('lux', 'Lux')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='kitchens_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='new_construction',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='orientation',
            field=models.CharField(blank=True, choices=[('north', 'North'), ('northeast', 'Northeast'), ('east', 'East'), ('southeast', 'Southeast'), ('south', 'South'), ('southwest', 'Southwest'), ('west', 'West'), ('northwest', 'Northwest')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='partitioning',
            field=models.CharField(blank=True, choices=[('open-space', 'Open-space'), ('circuit', 'Circuit'), ('semidetached', 'Semi-detached'), ('detached', 'Detached')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='rooms_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_field',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_util',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='front_line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_field',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_util',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='balconies_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='bathrooms_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='comfort',
            field=models.CharField(blank=True, choices=[('incomplete', 'Incomplete'), ('active', 'Active'), ('transacted', 'Transacted'), ('withdrawn', 'Withdrawn')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='construction_material',
            field=models.CharField(blank=True, choices=[('brick', 'Brick'), ('concrete', 'Concrete'), ('bca', 'BCA'), ('wood', 'Wood')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='construction_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='front_line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='interior_state',
            field=models.CharField(blank=True, choices=[('classic', 'Classic'), ('semi-finished', 'Semi-finished'), ('finished', 'Finished'), ('unfinished', 'Unfinished'), ('lux', 'Lux')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='kitchens_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='new_construction',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='orientation',
            field=models.CharField(blank=True, choices=[('north', 'North'), ('northeast', 'Northeast'), ('east', 'East'), ('southeast', 'Southeast'), ('south', 'South'), ('southwest', 'Southwest'), ('west', 'West'), ('northwest', 'Northwest')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='partitioning',
            field=models.CharField(blank=True, choices=[('open-space', 'Open-space'), ('circuit', 'Circuit'), ('semidetached', 'Semi-detached'), ('detached', 'Detached')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='rooms_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_field',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_util',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
