# Generated by Django 3.1 on 2020-09-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0028_auto_20200928_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseattributes',
            name='floors',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True),
        ),
    ]
