# Generated by Django 3.1 on 2020-09-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0029_auto_20200928_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentattributes',
            name='comfort',
            field=models.CharField(blank=True, choices=[('one', 'One'), ('two', 'Two')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='comfort',
            field=models.CharField(blank=True, choices=[('one', 'One'), ('two', 'Two')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='comfort',
            field=models.CharField(blank=True, choices=[('one', 'One'), ('two', 'Two')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='comfort',
            field=models.CharField(blank=True, choices=[('one', 'One'), ('two', 'Two')], max_length=50, null=True),
        ),
    ]
