# Generated by Django 3.1 on 2020-09-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0030_auto_20200928_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='contract_number',
        ),
        migrations.RemoveField(
            model_name='property',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='exclusive',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price_minimum',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price_per_sqm',
        ),
        migrations.RemoveField(
            model_name='property',
            name='special_offer',
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='front_line',
            field=models.IntegerField(blank=True, default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_built',
            field=models.IntegerField(blank=True, default=234),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_field',
            field=models.IntegerField(blank=True, default=43),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_total',
            field=models.IntegerField(blank=True, default=53),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_util',
            field=models.IntegerField(blank=True, default=65),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='front_line',
            field=models.IntegerField(blank=True, default=43),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_built',
            field=models.IntegerField(blank=True, default=65),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_field',
            field=models.IntegerField(blank=True, default=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_total',
            field=models.IntegerField(blank=True, default=74),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_util',
            field=models.IntegerField(blank=True, default=47),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='front_line',
            field=models.IntegerField(blank=True, default=63),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_built',
            field=models.IntegerField(blank=True, default=74),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_field',
            field=models.IntegerField(blank=True, default=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_total',
            field=models.IntegerField(blank=True, default=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_util',
            field=models.IntegerField(blank=True, default=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='front_line',
            field=models.IntegerField(blank=True, default=63),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_built',
            field=models.IntegerField(blank=True, default=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_field',
            field=models.IntegerField(blank=True, default=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_total',
            field=models.IntegerField(blank=True, default=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_util',
            field=models.IntegerField(blank=True, default=37),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='front_line',
            field=models.IntegerField(blank=True, default=74),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_built',
            field=models.IntegerField(blank=True, default=63),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_field',
            field=models.IntegerField(blank=True, default=74),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_total',
            field=models.IntegerField(blank=True, default=74),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_util',
            field=models.IntegerField(blank=True, default=74),
            preserve_default=False,
        ),
    ]
