# Generated by Django 3.1 on 2020-10-08 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20201007_1508'),
        ('properties', '0032_auto_20201003_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentattributes',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='description_private',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='description_sentimental',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='front_line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_field',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_util',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='description_private',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='description_sentimental',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='front_line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_field',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_util',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='description_private',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='description_sentimental',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='front_line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_field',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_util',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='description_private',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='description_sentimental',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='front_line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_field',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_util',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='property',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(blank=True, to='properties.Feature'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='description_private',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='description_sentimental',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='front_line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_built',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_field',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_util',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
