# Generated by Django 3.1 on 2020-10-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_auto_20200928_0855'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('properties', '0033_auto_20201008_1506'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('type', 'region', 'city', 'zone', 'street', 'number'), ('attributes_type', 'attributes_object_id')},
        ),
    ]
