# Generated by Django 3.1 on 2020-10-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0034_auto_20201009_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentattributes',
            name='pet_friendly',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='commercialattributes',
            name='pet_friendly',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='houseattributes',
            name='pet_friendly',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='studioattributes',
            name='pet_friendly',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
