# Generated by Django 3.1 on 2020-10-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0035_auto_20201015_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentattributes',
            name='garage',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='parking_spot',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='commercialattributes',
            name='garage',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='commercialattributes',
            name='parking_spot',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='houseattributes',
            name='garage',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='houseattributes',
            name='parking_spot',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='studioattributes',
            name='garage',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='studioattributes',
            name='parking_spot',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='partitioning',
            field=models.CharField(blank=True, choices=[('open-space', 'Open-space'), ('circuit', 'Circuit'), ('semidetached', 'Semi-decomandat'), ('detached', 'Decomandat'), ('vagon', 'Vagon')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='partitioning',
            field=models.CharField(blank=True, choices=[('open-space', 'Open-space'), ('circuit', 'Circuit'), ('semidetached', 'Semi-decomandat'), ('detached', 'Decomandat'), ('vagon', 'Vagon')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='partitioning',
            field=models.CharField(blank=True, choices=[('open-space', 'Open-space'), ('circuit', 'Circuit'), ('semidetached', 'Semi-decomandat'), ('detached', 'Decomandat'), ('vagon', 'Vagon')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='partitioning',
            field=models.CharField(blank=True, choices=[('open-space', 'Open-space'), ('circuit', 'Circuit'), ('semidetached', 'Semi-decomandat'), ('detached', 'Decomandat'), ('vagon', 'Vagon')], max_length=50, null=True),
        ),
    ]
