# Generated by Django 3.1 on 2020-10-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0036_auto_20201015_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentattributes',
            name='furnished',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='commercialattributes',
            name='furnished',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='houseattributes',
            name='furnished',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='studioattributes',
            name='furnished',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
