# Generated by Django 3.1 on 2020-10-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0039_auto_20201016_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
