# Generated by Django 3.1 on 2020-10-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0041_auto_20201019_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentattributes',
            name='attic',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='ground_floor',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='top_floor',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='commercialattributes',
            name='attic',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='commercialattributes',
            name='ground_floor',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='commercialattributes',
            name='top_floor',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='houseattributes',
            name='attic',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='houseattributes',
            name='ground_floor',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='houseattributes',
            name='top_floor',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='studioattributes',
            name='attic',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='studioattributes',
            name='ground_floor',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='studioattributes',
            name='top_floor',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='floor',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='floor',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='floor',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='floor',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True),
        ),
    ]
