# Generated by Django 3.1 on 2020-10-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0043_auto_20201019_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmentattributes',
            old_name='attic',
            new_name='mansard',
        ),
        migrations.RenameField(
            model_name='commercialattributes',
            old_name='attic',
            new_name='mansard',
        ),
        migrations.RenameField(
            model_name='houseattributes',
            old_name='attic',
            new_name='mansard',
        ),
        migrations.RenameField(
            model_name='studioattributes',
            old_name='attic',
            new_name='mansard',
        ),
    ]
