# Generated by Django 3.1 on 2020-10-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0044_auto_20201021_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commercialattributes',
            name='floors',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True),
        ),
    ]
