# Generated by Django 3.1 on 2020-11-04 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_auto_20201104_2207'),
        ('properties', '0046_auto_20201030_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentattributes',
            name='partitioning',
            field=models.CharField(blank=True, choices=[('open-space', 'Open-space'), ('circuit', 'Circuit'), ('semidetached', 'Semi-Detached'), ('detached', 'Detached'), ('wagon', 'Wagon')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='partitioning',
            field=models.CharField(blank=True, choices=[('open-space', 'Open-space'), ('circuit', 'Circuit'), ('semidetached', 'Semi-Detached'), ('detached', 'Detached'), ('wagon', 'Wagon')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='partitioning',
            field=models.CharField(blank=True, choices=[('open-space', 'Open-space'), ('circuit', 'Circuit'), ('semidetached', 'Semi-Detached'), ('detached', 'Detached'), ('wagon', 'Wagon')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='property',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='property',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.street', verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='property',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.zone', verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='partitioning',
            field=models.CharField(blank=True, choices=[('open-space', 'Open-space'), ('circuit', 'Circuit'), ('semidetached', 'Semi-Detached'), ('detached', 'Detached'), ('wagon', 'Wagon')], max_length=50, null=True),
        ),
    ]
