# Generated by Django 3.1 on 2020-11-09 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_auto_20201109_2130'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offices', '0004_auto_20201106_1534'),
        ('properties', '0047_auto_20201104_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentattributes',
            name='balconies_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Balconies Number'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='bathrooms_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Bathrooms Number'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='comfort',
            field=models.CharField(blank=True, choices=[('one', 'One'), ('two', 'Two')], max_length=50, null=True, verbose_name='Comfort'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='construction_material',
            field=models.CharField(blank=True, choices=[('brick', 'Brick'), ('concrete', 'Concrete'), ('bca', 'BCA'), ('wood', 'Wood')], max_length=50, null=True, verbose_name='Construction Material'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='construction_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Construction Year'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='description_private',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description Private'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='description_sentimental',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description Sentimental'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='energy_class',
            field=models.CharField(blank=True, choices=[('a2plus', 'A++'), ('a1plus', 'A+'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F'), ('g', 'G')], max_length=20, null=True, verbose_name='Energy Class'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='floor',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='Floor'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='floors',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='Floors'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front Line'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='furnished',
            field=models.BooleanField(default=False, verbose_name='Furnished'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='garage',
            field=models.BooleanField(default=False, verbose_name='Garage'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='ground_floor',
            field=models.BooleanField(default=False, verbose_name='Ground Floor'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='interior_state',
            field=models.CharField(blank=True, choices=[('classic', 'Classic'), ('semi-finished', 'Semi-finished'), ('finished', 'Finished'), ('unfinished', 'Unfinished'), ('lux', 'Lux')], max_length=50, null=True, verbose_name='Interior State'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='key_possession',
            field=models.BooleanField(default=False, verbose_name='Key Possession'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='kitchens_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Kitchens Number'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='mansard',
            field=models.BooleanField(default=False, verbose_name='Mansard'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='new_construction',
            field=models.BooleanField(default=False, verbose_name='New Construction'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='orientation',
            field=models.CharField(blank=True, choices=[('north', 'North'), ('northeast', 'Northeast'), ('east', 'East'), ('southeast', 'Southeast'), ('south', 'South'), ('southwest', 'Southwest'), ('west', 'West'), ('northwest', 'Northwest')], max_length=50, null=True, verbose_name='Orientation'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='parking_spot',
            field=models.BooleanField(default=False, verbose_name='Parking Spot'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='partitioning',
            field=models.CharField(blank=True, choices=[('open-space', 'Open-space'), ('circuit', 'Circuit'), ('semidetached', 'Semi-Detached'), ('detached', 'Detached'), ('wagon', 'Wagon')], max_length=50, null=True, verbose_name='Partitioning'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='pet_friendly',
            field=models.BooleanField(default=False, verbose_name='Pet Friendly'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='rooms_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='Rooms Number'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface Built'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface Field'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface Total'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface Util'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='top_floor',
            field=models.BooleanField(default=False, verbose_name='Top Floor'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='balconies_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Balconies Number'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='bathrooms_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Bathrooms Number'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='comfort',
            field=models.CharField(blank=True, choices=[('one', 'One'), ('two', 'Two')], max_length=50, null=True, verbose_name='Comfort'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='construction_material',
            field=models.CharField(blank=True, choices=[('brick', 'Brick'), ('concrete', 'Concrete'), ('bca', 'BCA'), ('wood', 'Wood')], max_length=50, null=True, verbose_name='Construction Material'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='construction_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Construction Year'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='description_private',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description Private'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='description_sentimental',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description Sentimental'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='energy_class',
            field=models.CharField(blank=True, choices=[('a2plus', 'A++'), ('a1plus', 'A+'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F'), ('g', 'G')], max_length=20, null=True, verbose_name='Energy Class'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='floor',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='Floor'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='floors',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='Floors'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front Line'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='furnished',
            field=models.BooleanField(default=False, verbose_name='Furnished'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='garage',
            field=models.BooleanField(default=False, verbose_name='Garage'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='ground_floor',
            field=models.BooleanField(default=False, verbose_name='Ground Floor'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='interior_state',
            field=models.CharField(blank=True, choices=[('classic', 'Classic'), ('semi-finished', 'Semi-finished'), ('finished', 'Finished'), ('unfinished', 'Unfinished'), ('lux', 'Lux')], max_length=50, null=True, verbose_name='Interior State'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='key_possession',
            field=models.BooleanField(default=False, verbose_name='Key Possession'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='kitchens_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Kitchens Number'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='mansard',
            field=models.BooleanField(default=False, verbose_name='Mansard'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='new_construction',
            field=models.BooleanField(default=False, verbose_name='New Construction'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='orientation',
            field=models.CharField(blank=True, choices=[('north', 'North'), ('northeast', 'Northeast'), ('east', 'East'), ('southeast', 'Southeast'), ('south', 'South'), ('southwest', 'Southwest'), ('west', 'West'), ('northwest', 'Northwest')], max_length=50, null=True, verbose_name='Orientation'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='parking_spot',
            field=models.BooleanField(default=False, verbose_name='Parking Spot'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='partitioning',
            field=models.CharField(blank=True, choices=[('open-space', 'Open-space'), ('circuit', 'Circuit'), ('semidetached', 'Semi-Detached'), ('detached', 'Detached'), ('wagon', 'Wagon')], max_length=50, null=True, verbose_name='Partitioning'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='pet_friendly',
            field=models.BooleanField(default=False, verbose_name='Pet Friendly'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='rooms_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='Rooms Number'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface Built'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface Field'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface Total'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface Util'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='top_floor',
            field=models.BooleanField(default=False, verbose_name='Top Floor'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='properties.featuregroup', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='featuregroup',
            name='display_name',
            field=models.CharField(max_length=200, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='featuregroup',
            name='property_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('studio', 'Studio'), ('commercial', 'Commercial space'), ('land', 'Land')], max_length=56, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='balconies_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Balconies Number'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='bathrooms_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Bathrooms Number'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='comfort',
            field=models.CharField(blank=True, choices=[('one', 'One'), ('two', 'Two')], max_length=50, null=True, verbose_name='Comfort'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='construction_material',
            field=models.CharField(blank=True, choices=[('brick', 'Brick'), ('concrete', 'Concrete'), ('bca', 'BCA'), ('wood', 'Wood')], max_length=50, null=True, verbose_name='Construction Material'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='construction_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Construction Year'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='description_private',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description Private'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='description_sentimental',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description Sentimental'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='energy_class',
            field=models.CharField(blank=True, choices=[('a2plus', 'A++'), ('a1plus', 'A+'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F'), ('g', 'G')], max_length=20, null=True, verbose_name='Energy Class'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='floor',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='Floor'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='floors',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='Floors'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front Line'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='furnished',
            field=models.BooleanField(default=False, verbose_name='Furnished'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='garage',
            field=models.BooleanField(default=False, verbose_name='Garage'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='ground_floor',
            field=models.BooleanField(default=False, verbose_name='Ground Floor'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='interior_state',
            field=models.CharField(blank=True, choices=[('classic', 'Classic'), ('semi-finished', 'Semi-finished'), ('finished', 'Finished'), ('unfinished', 'Unfinished'), ('lux', 'Lux')], max_length=50, null=True, verbose_name='Interior State'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='key_possession',
            field=models.BooleanField(default=False, verbose_name='Key Possession'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='kitchens_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Kitchens Number'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='mansard',
            field=models.BooleanField(default=False, verbose_name='Mansard'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='new_construction',
            field=models.BooleanField(default=False, verbose_name='New Construction'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='orientation',
            field=models.CharField(blank=True, choices=[('north', 'North'), ('northeast', 'Northeast'), ('east', 'East'), ('southeast', 'Southeast'), ('south', 'South'), ('southwest', 'Southwest'), ('west', 'West'), ('northwest', 'Northwest')], max_length=50, null=True, verbose_name='Orientation'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='parking_spot',
            field=models.BooleanField(default=False, verbose_name='Parking Spot'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='partitioning',
            field=models.CharField(blank=True, choices=[('open-space', 'Open-space'), ('circuit', 'Circuit'), ('semidetached', 'Semi-Detached'), ('detached', 'Detached'), ('wagon', 'Wagon')], max_length=50, null=True, verbose_name='Partitioning'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='pet_friendly',
            field=models.BooleanField(default=False, verbose_name='Pet Friendly'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='rooms_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='Rooms Number'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface Built'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface Field'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface Total'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface Util'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='top_floor',
            field=models.BooleanField(default=False, verbose_name='Top Floor'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='description_private',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description Private'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='description_sentimental',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description Sentimental'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front Line'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface Built'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface Field'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface Total'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface Util'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='property',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='clients.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='property',
            name='contract_number',
            field=models.CharField(blank=True, max_length=70, verbose_name='Contract Number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='contract_type',
            field=models.CharField(blank=True, max_length=70, verbose_name='Contract Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='property',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='property',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(blank=True, to='properties.Feature', verbose_name='Features'),
        ),
        migrations.AlterField(
            model_name='property',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='offices.office', verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='property',
            name='promote_site',
            field=models.BooleanField(default=False, verbose_name='Promote Site'),
        ),
        migrations.AlterField(
            model_name='property',
            name='promote_site_homepage',
            field=models.BooleanField(default=False, verbose_name='Promote Site Homepage'),
        ),
        migrations.AlterField(
            model_name='property',
            name='promoted',
            field=models.BooleanField(default=False, verbose_name='Promoted'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('active', 'Active'), ('transacted', 'Transacted'), ('withdrawn', 'Withdrawn')], default='incomplete', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('studio', 'Studio'), ('commercial', 'Commercial space'), ('land', 'Land')], max_length=56, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='property',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='file',
            field=models.ImageField(max_length=255, upload_to=properties.models.image_upload_path, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Property'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='public',
            field=models.BooleanField(default=True, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='balconies_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Balconies Number'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='bathrooms_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Bathrooms Number'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='comfort',
            field=models.CharField(blank=True, choices=[('one', 'One'), ('two', 'Two')], max_length=50, null=True, verbose_name='Comfort'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='construction_material',
            field=models.CharField(blank=True, choices=[('brick', 'Brick'), ('concrete', 'Concrete'), ('bca', 'BCA'), ('wood', 'Wood')], max_length=50, null=True, verbose_name='Construction Material'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='construction_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Construction Year'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='description_private',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description Private'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='description_sentimental',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description Sentimental'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='energy_class',
            field=models.CharField(blank=True, choices=[('a2plus', 'A++'), ('a1plus', 'A+'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F'), ('g', 'G')], max_length=20, null=True, verbose_name='Energy Class'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='floor',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='Floor'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='floors',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='Floors'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front Line'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='furnished',
            field=models.BooleanField(default=False, verbose_name='Furnished'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='garage',
            field=models.BooleanField(default=False, verbose_name='Garage'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='ground_floor',
            field=models.BooleanField(default=False, verbose_name='Ground Floor'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='interior_state',
            field=models.CharField(blank=True, choices=[('classic', 'Classic'), ('semi-finished', 'Semi-finished'), ('finished', 'Finished'), ('unfinished', 'Unfinished'), ('lux', 'Lux')], max_length=50, null=True, verbose_name='Interior State'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='key_possession',
            field=models.BooleanField(default=False, verbose_name='Key Possession'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='kitchens_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Kitchens Number'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='mansard',
            field=models.BooleanField(default=False, verbose_name='Mansard'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='new_construction',
            field=models.BooleanField(default=False, verbose_name='New Construction'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='orientation',
            field=models.CharField(blank=True, choices=[('north', 'North'), ('northeast', 'Northeast'), ('east', 'East'), ('southeast', 'Southeast'), ('south', 'South'), ('southwest', 'Southwest'), ('west', 'West'), ('northwest', 'Northwest')], max_length=50, null=True, verbose_name='Orientation'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='parking_spot',
            field=models.BooleanField(default=False, verbose_name='Parking Spot'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='partitioning',
            field=models.CharField(blank=True, choices=[('open-space', 'Open-space'), ('circuit', 'Circuit'), ('semidetached', 'Semi-Detached'), ('detached', 'Detached'), ('wagon', 'Wagon')], max_length=50, null=True, verbose_name='Partitioning'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='pet_friendly',
            field=models.BooleanField(default=False, verbose_name='Pet Friendly'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='rooms_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='Rooms Number'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface Built'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface Field'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface Total'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface Util'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='top_floor',
            field=models.BooleanField(default=False, verbose_name='Top Floor'),
        ),
    ]
