# Generated by Django 3.1 on 2020-11-16 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0048_auto_20201109_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='status',
        ),
    ]
