# Generated by Django 3.1 on 2020-11-17 19:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0049_remove_property_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='file',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='image_path',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Image path'),
            preserve_default=False,
        ),
    ]
