# Generated by Django 3.1 on 2020-12-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0050_auto_20201117_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentattributes',
            name='heating_source',
            field=models.CharField(blank=True, choices=[('central_heating', 'Central heating in building'), ('individual_central_heating', 'Individual central heating'), ('underfloor_heating', 'Underfloor heating'), ('district_heating', 'District heating'), ('wood_central_heating', 'Wood Central Heating'), ('fireplace', 'Fireplace'), ('convectors', 'Convectors')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='commercialattributes',
            name='heating_source',
            field=models.CharField(blank=True, choices=[('central_heating', 'Central heating in building'), ('individual_central_heating', 'Individual central heating'), ('underfloor_heating', 'Underfloor heating'), ('district_heating', 'District heating'), ('wood_central_heating', 'Wood Central Heating'), ('fireplace', 'Fireplace'), ('convectors', 'Convectors')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='houseattributes',
            name='heating_source',
            field=models.CharField(blank=True, choices=[('central_heating', 'Central heating in building'), ('individual_central_heating', 'Individual central heating'), ('underfloor_heating', 'Underfloor heating'), ('district_heating', 'District heating'), ('wood_central_heating', 'Wood Central Heating'), ('fireplace', 'Fireplace'), ('convectors', 'Convectors')], max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='studioattributes',
            name='heating_source',
            field=models.CharField(blank=True, choices=[('central_heating', 'Central heating in building'), ('individual_central_heating', 'Individual central heating'), ('underfloor_heating', 'Underfloor heating'), ('district_heating', 'District heating'), ('wood_central_heating', 'Wood Central Heating'), ('fireplace', 'Fireplace'), ('convectors', 'Convectors')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='comfort',
            field=models.CharField(blank=True, choices=[('one', 'One'), ('two', 'Two'), ('increased', 'Increased'), ('unique', 'Unique')], max_length=50, null=True, verbose_name='Comfort'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='comfort',
            field=models.CharField(blank=True, choices=[('one', 'One'), ('two', 'Two'), ('increased', 'Increased'), ('unique', 'Unique')], max_length=50, null=True, verbose_name='Comfort'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='comfort',
            field=models.CharField(blank=True, choices=[('one', 'One'), ('two', 'Two'), ('increased', 'Increased'), ('unique', 'Unique')], max_length=50, null=True, verbose_name='Comfort'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='comfort',
            field=models.CharField(blank=True, choices=[('one', 'One'), ('two', 'Two'), ('increased', 'Increased'), ('unique', 'Unique')], max_length=50, null=True, verbose_name='Comfort'),
        ),
    ]
