# Generated by Django 3.1 on 2020-12-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_auto_20201104_2207'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('properties', '0051_auto_20201209_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='number',
            new_name='street_number',
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('attributes_type', 'attributes_object_id'), ('type', 'region', 'city', 'zone', 'street', 'street_number')},
        ),
    ]
