# Generated by Django 3.1 on 2020-12-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0052_auto_20201211_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentattributes',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description Public'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description Public'),
        ),
        migrations.AlterField(
            model_name='featuregroup',
            name='property_type',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('studio', 'Studio'), ('commercial', 'Commercial space'), ('land', 'Land')], max_length=56, null=True, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description Public'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description Public'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description Public'),
        ),
    ]
