# Generated by Django 3.1 on 2020-12-15 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0053_auto_20201215_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentattributes',
            name='ground_floor',
        ),
        migrations.RemoveField(
            model_name='apartmentattributes',
            name='mansard',
        ),
        migrations.RemoveField(
            model_name='apartmentattributes',
            name='new_construction',
        ),
        migrations.RemoveField(
            model_name='apartmentattributes',
            name='top_floor',
        ),
        migrations.RemoveField(
            model_name='commercialattributes',
            name='ground_floor',
        ),
        migrations.RemoveField(
            model_name='commercialattributes',
            name='mansard',
        ),
        migrations.RemoveField(
            model_name='commercialattributes',
            name='new_construction',
        ),
        migrations.RemoveField(
            model_name='commercialattributes',
            name='top_floor',
        ),
        migrations.RemoveField(
            model_name='houseattributes',
            name='ground_floor',
        ),
        migrations.RemoveField(
            model_name='houseattributes',
            name='mansard',
        ),
        migrations.RemoveField(
            model_name='houseattributes',
            name='new_construction',
        ),
        migrations.RemoveField(
            model_name='houseattributes',
            name='top_floor',
        ),
        migrations.RemoveField(
            model_name='studioattributes',
            name='ground_floor',
        ),
        migrations.RemoveField(
            model_name='studioattributes',
            name='mansard',
        ),
        migrations.RemoveField(
            model_name='studioattributes',
            name='new_construction',
        ),
        migrations.RemoveField(
            model_name='studioattributes',
            name='top_floor',
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='internet',
            field=models.CharField(blank=True, choices=[('fiber_optics', 'Fiber Optics'), ('cable', 'Cable')], max_length=256, null=True, verbose_name='Internet Connection'),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='windows',
            field=models.CharField(blank=True, choices=[('double_glazing', 'Double Glazing Glass'), ('wood_glass', 'Wood and Glass')], max_length=256, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='commercialattributes',
            name='internet',
            field=models.CharField(blank=True, choices=[('fiber_optics', 'Fiber Optics'), ('cable', 'Cable')], max_length=256, null=True, verbose_name='Internet Connection'),
        ),
        migrations.AddField(
            model_name='commercialattributes',
            name='windows',
            field=models.CharField(blank=True, choices=[('double_glazing', 'Double Glazing Glass'), ('wood_glass', 'Wood and Glass')], max_length=256, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='houseattributes',
            name='internet',
            field=models.CharField(blank=True, choices=[('fiber_optics', 'Fiber Optics'), ('cable', 'Cable')], max_length=256, null=True, verbose_name='Internet Connection'),
        ),
        migrations.AddField(
            model_name='houseattributes',
            name='windows',
            field=models.CharField(blank=True, choices=[('double_glazing', 'Double Glazing Glass'), ('wood_glass', 'Wood and Glass')], max_length=256, null=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='studioattributes',
            name='internet',
            field=models.CharField(blank=True, choices=[('fiber_optics', 'Fiber Optics'), ('cable', 'Cable')], max_length=256, null=True, verbose_name='Internet Connection'),
        ),
        migrations.AddField(
            model_name='studioattributes',
            name='windows',
            field=models.CharField(blank=True, choices=[('double_glazing', 'Double Glazing Glass'), ('wood_glass', 'Wood and Glass')], max_length=256, null=True, verbose_name='Windows'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='furnished',
            field=models.BooleanField(blank=True, choices=[('semi_furnished', 'Semi-Furnished'), ('furnished_kitchen', 'Furnished Kitchen'), ('furnished_modern', 'Furnished with modern utilities'), ('furnished_classic', 'Furnished with classic utilities'), ('lux', 'Luxurious')], max_length=256, null=True, verbose_name='Furnished'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='garage',
            field=models.CharField(blank=True, choices=[('garage', 'Garage'), ('underground_garage', 'Undeground Garage')], max_length=256, null=True, verbose_name='Garage'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='interior_state',
            field=models.CharField(blank=True, choices=[('classic', 'Classic'), ('semi-finished', 'Semi-finished'), ('finished', 'Finished'), ('unfinished', 'Unfinished'), ('lux', 'Luxurious')], max_length=50, null=True, verbose_name='Interior State'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='furnished',
            field=models.BooleanField(blank=True, choices=[('semi_furnished', 'Semi-Furnished'), ('furnished_kitchen', 'Furnished Kitchen'), ('furnished_modern', 'Furnished with modern utilities'), ('furnished_classic', 'Furnished with classic utilities'), ('lux', 'Luxurious')], max_length=256, null=True, verbose_name='Furnished'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='garage',
            field=models.CharField(blank=True, choices=[('garage', 'Garage'), ('underground_garage', 'Undeground Garage')], max_length=256, null=True, verbose_name='Garage'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='interior_state',
            field=models.CharField(blank=True, choices=[('classic', 'Classic'), ('semi-finished', 'Semi-finished'), ('finished', 'Finished'), ('unfinished', 'Unfinished'), ('lux', 'Luxurious')], max_length=50, null=True, verbose_name='Interior State'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='furnished',
            field=models.BooleanField(blank=True, choices=[('semi_furnished', 'Semi-Furnished'), ('furnished_kitchen', 'Furnished Kitchen'), ('furnished_modern', 'Furnished with modern utilities'), ('furnished_classic', 'Furnished with classic utilities'), ('lux', 'Luxurious')], max_length=256, null=True, verbose_name='Furnished'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='garage',
            field=models.CharField(blank=True, choices=[('garage', 'Garage'), ('underground_garage', 'Undeground Garage')], max_length=256, null=True, verbose_name='Garage'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='interior_state',
            field=models.CharField(blank=True, choices=[('classic', 'Classic'), ('semi-finished', 'Semi-finished'), ('finished', 'Finished'), ('unfinished', 'Unfinished'), ('lux', 'Luxurious')], max_length=50, null=True, verbose_name='Interior State'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='furnished',
            field=models.BooleanField(blank=True, choices=[('semi_furnished', 'Semi-Furnished'), ('furnished_kitchen', 'Furnished Kitchen'), ('furnished_modern', 'Furnished with modern utilities'), ('furnished_classic', 'Furnished with classic utilities'), ('lux', 'Luxurious')], max_length=256, null=True, verbose_name='Furnished'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='garage',
            field=models.CharField(blank=True, choices=[('garage', 'Garage'), ('underground_garage', 'Undeground Garage')], max_length=256, null=True, verbose_name='Garage'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='interior_state',
            field=models.CharField(blank=True, choices=[('classic', 'Classic'), ('semi-finished', 'Semi-finished'), ('finished', 'Finished'), ('unfinished', 'Unfinished'), ('lux', 'Luxurious')], max_length=50, null=True, verbose_name='Interior State'),
        ),
    ]
