# Generated by Django 3.1 on 2020-12-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0054_auto_20201215_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentattributes',
            name='furnished',
            field=models.BooleanField(blank=True, choices=[('semi_furnished', 'Semi-furnished'), ('furnished_kitchen', 'Furnished kitchen'), ('furnished_modern', 'Furnished with modern utilities'), ('furnished_classic', 'Furnished with classic utilities'), ('lux', 'Luxurious')], max_length=256, null=True, verbose_name='Furnished'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='garage',
            field=models.CharField(blank=True, choices=[('garage', 'Garage'), ('underground_garage', 'Underground garage')], max_length=256, null=True, verbose_name='Garage'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='windows',
            field=models.CharField(blank=True, choices=[('double_glazing', 'Double glazing glass'), ('wood_glass', 'Wood and glass')], max_length=256, null=True, verbose_name='Windows'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='furnished',
            field=models.BooleanField(blank=True, choices=[('semi_furnished', 'Semi-furnished'), ('furnished_kitchen', 'Furnished kitchen'), ('furnished_modern', 'Furnished with modern utilities'), ('furnished_classic', 'Furnished with classic utilities'), ('lux', 'Luxurious')], max_length=256, null=True, verbose_name='Furnished'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='garage',
            field=models.CharField(blank=True, choices=[('garage', 'Garage'), ('underground_garage', 'Underground garage')], max_length=256, null=True, verbose_name='Garage'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='windows',
            field=models.CharField(blank=True, choices=[('double_glazing', 'Double glazing glass'), ('wood_glass', 'Wood and glass')], max_length=256, null=True, verbose_name='Windows'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='furnished',
            field=models.BooleanField(blank=True, choices=[('semi_furnished', 'Semi-furnished'), ('furnished_kitchen', 'Furnished kitchen'), ('furnished_modern', 'Furnished with modern utilities'), ('furnished_classic', 'Furnished with classic utilities'), ('lux', 'Luxurious')], max_length=256, null=True, verbose_name='Furnished'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='garage',
            field=models.CharField(blank=True, choices=[('garage', 'Garage'), ('underground_garage', 'Underground garage')], max_length=256, null=True, verbose_name='Garage'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='windows',
            field=models.CharField(blank=True, choices=[('double_glazing', 'Double glazing glass'), ('wood_glass', 'Wood and glass')], max_length=256, null=True, verbose_name='Windows'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='furnished',
            field=models.BooleanField(blank=True, choices=[('semi_furnished', 'Semi-furnished'), ('furnished_kitchen', 'Furnished kitchen'), ('furnished_modern', 'Furnished with modern utilities'), ('furnished_classic', 'Furnished with classic utilities'), ('lux', 'Luxurious')], max_length=256, null=True, verbose_name='Furnished'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='garage',
            field=models.CharField(blank=True, choices=[('garage', 'Garage'), ('underground_garage', 'Underground garage')], max_length=256, null=True, verbose_name='Garage'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='windows',
            field=models.CharField(blank=True, choices=[('double_glazing', 'Double glazing glass'), ('wood_glass', 'Wood and glass')], max_length=256, null=True, verbose_name='Windows'),
        ),
    ]
