# Generated by Django 3.1 on 2020-12-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0055_auto_20201215_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentattributes',
            name='key_possession',
        ),
        migrations.RemoveField(
            model_name='apartmentattributes',
            name='parking_spot',
        ),
        migrations.RemoveField(
            model_name='apartmentattributes',
            name='pet_friendly',
        ),
        migrations.RemoveField(
            model_name='commercialattributes',
            name='key_possession',
        ),
        migrations.RemoveField(
            model_name='commercialattributes',
            name='parking_spot',
        ),
        migrations.RemoveField(
            model_name='commercialattributes',
            name='pet_friendly',
        ),
        migrations.RemoveField(
            model_name='houseattributes',
            name='key_possession',
        ),
        migrations.RemoveField(
            model_name='houseattributes',
            name='parking_spot',
        ),
        migrations.RemoveField(
            model_name='houseattributes',
            name='pet_friendly',
        ),
        migrations.RemoveField(
            model_name='studioattributes',
            name='key_possession',
        ),
        migrations.RemoveField(
            model_name='studioattributes',
            name='parking_spot',
        ),
        migrations.RemoveField(
            model_name='studioattributes',
            name='pet_friendly',
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='furnished',
            field=models.CharField(blank=True, choices=[('semi_furnished', 'Semi-furnished'), ('furnished_kitchen', 'Furnished kitchen'), ('furnished_modern', 'Furnished with modern utilities'), ('furnished_classic', 'Furnished with classic utilities'), ('lux', 'Luxurious')], max_length=256, null=True, verbose_name='Furnished'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='furnished',
            field=models.CharField(blank=True, choices=[('semi_furnished', 'Semi-furnished'), ('furnished_kitchen', 'Furnished kitchen'), ('furnished_modern', 'Furnished with modern utilities'), ('furnished_classic', 'Furnished with classic utilities'), ('lux', 'Luxurious')], max_length=256, null=True, verbose_name='Furnished'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='furnished',
            field=models.CharField(blank=True, choices=[('semi_furnished', 'Semi-furnished'), ('furnished_kitchen', 'Furnished kitchen'), ('furnished_modern', 'Furnished with modern utilities'), ('furnished_classic', 'Furnished with classic utilities'), ('lux', 'Luxurious')], max_length=256, null=True, verbose_name='Furnished'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='furnished',
            field=models.CharField(blank=True, choices=[('semi_furnished', 'Semi-furnished'), ('furnished_kitchen', 'Furnished kitchen'), ('furnished_modern', 'Furnished with modern utilities'), ('furnished_classic', 'Furnished with classic utilities'), ('lux', 'Luxurious')], max_length=256, null=True, verbose_name='Furnished'),
        ),
    ]
