# Generated by Django 3.1 on 2020-12-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0056_auto_20201215_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuregroup',
            name='is_filtered',
            field=models.BooleanField(default=False, verbose_name='Is Filtered'),
        ),
    ]
