# Generated by Django 3.1 on 2020-12-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0058_auto_20201216_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuregroup',
            name='is_filtered',
        ),
        migrations.AddField(
            model_name='feature',
            name='is_filtered',
            field=models.BooleanField(default=False, verbose_name='Is Filtered'),
        ),
    ]
