# Generated by Django 3.1 on 2020-12-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0059_auto_20201216_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='position',
            field=models.PositiveIntegerField(default=100, verbose_name='Image Position'),
        ),
    ]
