# Generated by Django 3.1 on 2020-12-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0061_auto_20201219_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentattributes',
            name='built',
            field=models.CharField(blank=True, choices=[('before_1960', 'Before 1960'), ('between_1960_200', 'Between 1960 - 2000'), ('after_200', 'After 2000')], max_length=256, null=True, verbose_name='Built'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='built',
            field=models.CharField(blank=True, choices=[('before_1960', 'Before 1960'), ('between_1960_200', 'Between 1960 - 2000'), ('after_200', 'After 2000')], max_length=256, null=True, verbose_name='Built'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='built',
            field=models.CharField(blank=True, choices=[('before_1960', 'Before 1960'), ('between_1960_200', 'Between 1960 - 2000'), ('after_200', 'After 2000')], max_length=256, null=True, verbose_name='Built'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='built',
            field=models.CharField(blank=True, choices=[('before_1960', 'Before 1960'), ('between_1960_200', 'Between 1960 - 2000'), ('after_200', 'After 2000')], max_length=256, null=True, verbose_name='Built'),
        ),
    ]
