# Generated by Django 3.1 on 2021-01-02 20:34

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0062_auto_20201219_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentattributes',
            name='construction_material',
            field=models.CharField(blank=True, choices=[('brick', 'Brick'), ('concrete', 'Concrete'), ('bca', 'BCA'), ('wood', 'Wood')], max_length=50, null=True, verbose_name='Construction material'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='construction_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Construction year'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description public'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='energy_class',
            field=models.CharField(blank=True, choices=[('a2plus', 'A++'), ('a1plus', 'A+'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F'), ('g', 'G')], max_length=20, null=True, verbose_name='Energy class'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front line'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='heating_source',
            field=models.CharField(blank=True, choices=[('central_heating', 'Central heating in building'), ('individual_central_heating', 'Individual central heating'), ('underfloor_heating', 'Underfloor heating'), ('district_heating', 'District heating'), ('wood_central_heating', 'Wood central heating'), ('fireplace', 'Fireplace'), ('convectors', 'Convectors')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='interior_state',
            field=models.CharField(blank=True, choices=[('classic', 'Classic'), ('semi-finished', 'Semi-finished'), ('finished', 'Finished'), ('unfinished', 'Unfinished'), ('lux', 'Luxurious')], max_length=50, null=True, verbose_name='Interior state'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='internet',
            field=models.CharField(blank=True, choices=[('fiber_optics', 'Fiber optics'), ('cable', 'Cable')], max_length=256, null=True, verbose_name='Internet connection'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='partitioning',
            field=models.CharField(blank=True, choices=[('open-space', 'Open-space'), ('circuit', 'Circuit'), ('semidetached', 'Semi-detached'), ('detached', 'Detached'), ('wagon', 'Wagon')], max_length=50, null=True, verbose_name='Partitioning'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface built'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface field'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface total'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface util'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='construction_material',
            field=models.CharField(blank=True, choices=[('brick', 'Brick'), ('concrete', 'Concrete'), ('bca', 'BCA'), ('wood', 'Wood')], max_length=50, null=True, verbose_name='Construction material'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='construction_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Construction year'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description public'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='energy_class',
            field=models.CharField(blank=True, choices=[('a2plus', 'A++'), ('a1plus', 'A+'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F'), ('g', 'G')], max_length=20, null=True, verbose_name='Energy class'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front line'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='heating_source',
            field=models.CharField(blank=True, choices=[('central_heating', 'Central heating in building'), ('individual_central_heating', 'Individual central heating'), ('underfloor_heating', 'Underfloor heating'), ('district_heating', 'District heating'), ('wood_central_heating', 'Wood central heating'), ('fireplace', 'Fireplace'), ('convectors', 'Convectors')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='interior_state',
            field=models.CharField(blank=True, choices=[('classic', 'Classic'), ('semi-finished', 'Semi-finished'), ('finished', 'Finished'), ('unfinished', 'Unfinished'), ('lux', 'Luxurious')], max_length=50, null=True, verbose_name='Interior state'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='internet',
            field=models.CharField(blank=True, choices=[('fiber_optics', 'Fiber optics'), ('cable', 'Cable')], max_length=256, null=True, verbose_name='Internet connection'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='partitioning',
            field=models.CharField(blank=True, choices=[('open-space', 'Open-space'), ('circuit', 'Circuit'), ('semidetached', 'Semi-detached'), ('detached', 'Detached'), ('wagon', 'Wagon')], max_length=50, null=True, verbose_name='Partitioning'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface built'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface field'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface total'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface util'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='is_filtered',
            field=models.BooleanField(default=False, verbose_name='Is filtered'),
        ),
        migrations.AlterField(
            model_name='featuregroup',
            name='display_name',
            field=models.CharField(max_length=200, verbose_name='Display name'),
        ),
        migrations.AlterField(
            model_name='featuregroup',
            name='property_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('studio', 'Studio'), ('commercial', 'Commercial space'), ('land', 'Land')], max_length=56, null=True, verbose_name='Property type'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='construction_material',
            field=models.CharField(blank=True, choices=[('brick', 'Brick'), ('concrete', 'Concrete'), ('bca', 'BCA'), ('wood', 'Wood')], max_length=50, null=True, verbose_name='Construction material'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='construction_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Construction year'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description public'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='energy_class',
            field=models.CharField(blank=True, choices=[('a2plus', 'A++'), ('a1plus', 'A+'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F'), ('g', 'G')], max_length=20, null=True, verbose_name='Energy class'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front line'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='heating_source',
            field=models.CharField(blank=True, choices=[('central_heating', 'Central heating in building'), ('individual_central_heating', 'Individual central heating'), ('underfloor_heating', 'Underfloor heating'), ('district_heating', 'District heating'), ('wood_central_heating', 'Wood central heating'), ('fireplace', 'Fireplace'), ('convectors', 'Convectors')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='interior_state',
            field=models.CharField(blank=True, choices=[('classic', 'Classic'), ('semi-finished', 'Semi-finished'), ('finished', 'Finished'), ('unfinished', 'Unfinished'), ('lux', 'Luxurious')], max_length=50, null=True, verbose_name='Interior state'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='internet',
            field=models.CharField(blank=True, choices=[('fiber_optics', 'Fiber optics'), ('cable', 'Cable')], max_length=256, null=True, verbose_name='Internet connection'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='partitioning',
            field=models.CharField(blank=True, choices=[('open-space', 'Open-space'), ('circuit', 'Circuit'), ('semidetached', 'Semi-detached'), ('detached', 'Detached'), ('wagon', 'Wagon')], max_length=50, null=True, verbose_name='Partitioning'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface built'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface field'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface total'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface util'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description public'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front line'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface built'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface field'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface total'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface util'),
        ),
        migrations.AlterField(
            model_name='property',
            name='contract_number',
            field=models.CharField(blank=True, max_length=70, verbose_name='Contract number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='contract_type',
            field=models.CharField(blank=True, max_length=70, verbose_name='Contract type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='property',
            name='promote_site',
            field=models.BooleanField(default=False, verbose_name='Promote site'),
        ),
        migrations.AlterField(
            model_name='property',
            name='promote_site_homepage',
            field=models.BooleanField(default=False, verbose_name='Promote site homepage'),
        ),
        migrations.AlterField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='construction_material',
            field=models.CharField(blank=True, choices=[('brick', 'Brick'), ('concrete', 'Concrete'), ('bca', 'BCA'), ('wood', 'Wood')], max_length=50, null=True, verbose_name='Construction material'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='construction_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Construction year'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description public'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='energy_class',
            field=models.CharField(blank=True, choices=[('a2plus', 'A++'), ('a1plus', 'A+'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E'), ('f', 'F'), ('g', 'G')], max_length=20, null=True, verbose_name='Energy class'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front line'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='heating_source',
            field=models.CharField(blank=True, choices=[('central_heating', 'Central heating in building'), ('individual_central_heating', 'Individual central heating'), ('underfloor_heating', 'Underfloor heating'), ('district_heating', 'District heating'), ('wood_central_heating', 'Wood central heating'), ('fireplace', 'Fireplace'), ('convectors', 'Convectors')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='interior_state',
            field=models.CharField(blank=True, choices=[('classic', 'Classic'), ('semi-finished', 'Semi-finished'), ('finished', 'Finished'), ('unfinished', 'Unfinished'), ('lux', 'Luxurious')], max_length=50, null=True, verbose_name='Interior state'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='internet',
            field=models.CharField(blank=True, choices=[('fiber_optics', 'Fiber optics'), ('cable', 'Cable')], max_length=256, null=True, verbose_name='Internet connection'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='partitioning',
            field=models.CharField(blank=True, choices=[('open-space', 'Open-space'), ('circuit', 'Circuit'), ('semidetached', 'Semi-detached'), ('detached', 'Detached'), ('wagon', 'Wagon')], max_length=50, null=True, verbose_name='Partitioning'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface built'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface field'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface total'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface util'),
        ),
    ]
