# Generated by Django 3.1 on 2021-01-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0064_auto_20210102_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartmentattributes',
            old_name='internet',
            new_name='internet_connection',
        ),
        migrations.RenameField(
            model_name='commercialattributes',
            old_name='internet',
            new_name='internet_connection',
        ),
        migrations.RenameField(
            model_name='houseattributes',
            old_name='internet',
            new_name='internet_connection',
        ),
        migrations.RenameField(
            model_name='studioattributes',
            old_name='internet',
            new_name='internet_connection',
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='ground_floor',
            field=models.BooleanField(default=False, verbose_name='Is ground floor'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='mansard',
            field=models.BooleanField(default=False, verbose_name='Is mansard'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='top_floor',
            field=models.BooleanField(default=False, verbose_name='Is top floor'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='ground_floor',
            field=models.BooleanField(default=False, verbose_name='Is ground floor'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='mansard',
            field=models.BooleanField(default=False, verbose_name='Is mansard'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='top_floor',
            field=models.BooleanField(default=False, verbose_name='Is top floor'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='ground_floor',
            field=models.BooleanField(default=False, verbose_name='Is ground floor'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='mansard',
            field=models.BooleanField(default=False, verbose_name='Is mansard'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='top_floor',
            field=models.BooleanField(default=False, verbose_name='Is top floor'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='ground_floor',
            field=models.BooleanField(default=False, verbose_name='Is ground floor'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='mansard',
            field=models.BooleanField(default=False, verbose_name='Is mansard'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='top_floor',
            field=models.BooleanField(default=False, verbose_name='Is top floor'),
        ),
    ]
