# Generated by Django 3.1 on 2021-01-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0066_auto_20210103_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentattributes',
            name='description_private',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description private'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='description_sentimental',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description sentimental'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='rooms_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='Rooms number'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='description_private',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description private'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='description_sentimental',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description sentimental'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='rooms_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='Rooms number'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='description_private',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description private'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='description_sentimental',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description sentimental'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='rooms_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='Rooms number'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='description_private',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description private'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='description_sentimental',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description sentimental'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='description_private',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description private'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='description_sentimental',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description sentimental'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='rooms_number',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], null=True, verbose_name='Rooms number'),
        ),
    ]
