# Generated by Django 3.1 on 2021-01-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0067_auto_20210103_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='show_on_site',
            field=models.BooleanField(default=True, verbose_name='Show on site'),
        ),
    ]
