# Generated by Django 3.1 on 2021-01-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0068_propertyimage_show_on_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='show_on_site',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='hide_on_site',
            field=models.BooleanField(default=False, verbose_name='Hide on site'),
        ),
    ]
