# Generated by Django 3.1 on 2021-01-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0071_auto_20210119_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='contract_number',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Contract number'),
        ),
    ]
