# Generated by Django 3.1 on 2021-01-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0072_auto_20210120_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Apartment number'),
        ),
        migrations.AddField(
            model_name='property',
            name='block_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Bock number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='street_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Number'),
        ),
    ]
