# Generated by Django 3.1 on 2021-01-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0073_auto_20210120_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ap number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='street_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Street number'),
        ),
    ]
