# Generated by Django 3.1 on 2021-01-26 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('locations', '0010_auto_20201104_2207'),
        ('properties', '0074_auto_20210120_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartmentattributes',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='commercialattributes',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='houseattributes',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='studioattributes',
            name='floor',
        ),
        migrations.AddField(
            model_name='property',
            name='block_entrance_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Block entrance'),
        ),
        migrations.AddField(
            model_name='property',
            name='contract_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='floor',
            field=models.CharField(blank=True, choices=[('basement', 'Basement'), ('semi_basement', 'Semi Basement'), ('ground_floor', 'Ground Floor'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=20, null=True, verbose_name='Floor'),
        ),
        migrations.AlterField(
            model_name='property',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ap. number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='block_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Block number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='contract_number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)], verbose_name='Contract number'),
        ),
        migrations.AlterField(
            model_name='property',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('sale', 'Sale'), ('exclusive_sale', 'Exclusive sale'), ('rent', 'Rent'), ('exclusive_rent', 'Exclusive rent')], max_length=70, verbose_name='Contract type'),
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('attributes_type', 'attributes_object_id'), ('type', 'region', 'city', 'zone', 'street', 'street_number', 'block_number', 'apartment_number')},
        ),
    ]
