# Generated by Django 3.1 on 2021-02-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0075_auto_20210126_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='contract_date',
        ),
        migrations.RemoveField(
            model_name='property',
            name='contract_number',
        ),
        migrations.RemoveField(
            model_name='property',
            name='contract_type',
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='cadastral_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Cadastral number'),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='in_development',
            field=models.BooleanField(default=False, verbose_name='In development'),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='key_holding',
            field=models.BooleanField(default=False, verbose_name='Key holding'),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='land_registry',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Land registry'),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='new_building',
            field=models.BooleanField(default=False, verbose_name='New building'),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='topographic_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Topographic number'),
        ),
        migrations.AddField(
            model_name='commercialattributes',
            name='cadastral_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Cadastral number'),
        ),
        migrations.AddField(
            model_name='commercialattributes',
            name='in_development',
            field=models.BooleanField(default=False, verbose_name='In development'),
        ),
        migrations.AddField(
            model_name='commercialattributes',
            name='key_holding',
            field=models.BooleanField(default=False, verbose_name='Key holding'),
        ),
        migrations.AddField(
            model_name='commercialattributes',
            name='land_registry',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Land registry'),
        ),
        migrations.AddField(
            model_name='commercialattributes',
            name='new_building',
            field=models.BooleanField(default=False, verbose_name='New building'),
        ),
        migrations.AddField(
            model_name='commercialattributes',
            name='topographic_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Topographic number'),
        ),
        migrations.AddField(
            model_name='houseattributes',
            name='cadastral_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Cadastral number'),
        ),
        migrations.AddField(
            model_name='houseattributes',
            name='in_development',
            field=models.BooleanField(default=False, verbose_name='In development'),
        ),
        migrations.AddField(
            model_name='houseattributes',
            name='key_holding',
            field=models.BooleanField(default=False, verbose_name='Key holding'),
        ),
        migrations.AddField(
            model_name='houseattributes',
            name='land_registry',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Land registry'),
        ),
        migrations.AddField(
            model_name='houseattributes',
            name='new_building',
            field=models.BooleanField(default=False, verbose_name='New building'),
        ),
        migrations.AddField(
            model_name='houseattributes',
            name='topographic_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Topographic number'),
        ),
        migrations.AddField(
            model_name='property',
            name='video_tour',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Video tour'),
        ),
        migrations.AddField(
            model_name='property',
            name='virtual_tour',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Virtual tour'),
        ),
        migrations.AddField(
            model_name='studioattributes',
            name='cadastral_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Cadastral number'),
        ),
        migrations.AddField(
            model_name='studioattributes',
            name='in_development',
            field=models.BooleanField(default=False, verbose_name='In development'),
        ),
        migrations.AddField(
            model_name='studioattributes',
            name='key_holding',
            field=models.BooleanField(default=False, verbose_name='Key holding'),
        ),
        migrations.AddField(
            model_name='studioattributes',
            name='land_registry',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Land registry'),
        ),
        migrations.AddField(
            model_name='studioattributes',
            name='new_building',
            field=models.BooleanField(default=False, verbose_name='New building'),
        ),
        migrations.AddField(
            model_name='studioattributes',
            name='topographic_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Topographic number'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='built',
            field=models.CharField(blank=True, choices=[('before_1960', 'Before 1960'), ('between_1960_200', 'Between 1960 - 2000'), ('after_2000', 'After 2000')], max_length=256, null=True, verbose_name='Built'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='built',
            field=models.CharField(blank=True, choices=[('before_1960', 'Before 1960'), ('between_1960_200', 'Between 1960 - 2000'), ('after_2000', 'After 2000')], max_length=256, null=True, verbose_name='Built'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='built',
            field=models.CharField(blank=True, choices=[('before_1960', 'Before 1960'), ('between_1960_200', 'Between 1960 - 2000'), ('after_2000', 'After 2000')], max_length=256, null=True, verbose_name='Built'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.CharField(blank=True, choices=[('basement', 'Basement'), ('semi_basement', 'Semi Basement'), ('ground_floor', 'Ground Floor'), ('mansard', 'Mansard'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=20, null=True, verbose_name='Floor'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='built',
            field=models.CharField(blank=True, choices=[('before_1960', 'Before 1960'), ('between_1960_200', 'Between 1960 - 2000'), ('after_2000', 'After 2000')], max_length=256, null=True, verbose_name='Built'),
        ),
    ]
