# Generated by Django 3.1 on 2021-02-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0077_auto_20210208_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentattributes',
            name='heating_source',
            field=models.CharField(blank=True, choices=[('central_heating', 'Central heating in building'), ('individual_central_heating', 'Individual central heating'), ('underfloor_heating', 'Underfloor heating'), ('district_heating', 'District heating'), ('wood_central_heating', 'Wood central heating'), ('fireplace', 'Fireplace'), ('convectors', 'Convectors')], max_length=256, null=True, verbose_name='Heating source'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='heating_source',
            field=models.CharField(blank=True, choices=[('central_heating', 'Central heating in building'), ('individual_central_heating', 'Individual central heating'), ('underfloor_heating', 'Underfloor heating'), ('district_heating', 'District heating'), ('wood_central_heating', 'Wood central heating'), ('fireplace', 'Fireplace'), ('convectors', 'Convectors')], max_length=256, null=True, verbose_name='Heating source'),
        ),
        migrations.AlterField(
            model_name='hotelattributes',
            name='heating_source',
            field=models.CharField(blank=True, choices=[('central_heating', 'Central heating in building'), ('individual_central_heating', 'Individual central heating'), ('underfloor_heating', 'Underfloor heating'), ('district_heating', 'District heating'), ('wood_central_heating', 'Wood central heating'), ('fireplace', 'Fireplace'), ('convectors', 'Convectors')], max_length=256, null=True, verbose_name='Heating source'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='heating_source',
            field=models.CharField(blank=True, choices=[('central_heating', 'Central heating in building'), ('individual_central_heating', 'Individual central heating'), ('underfloor_heating', 'Underfloor heating'), ('district_heating', 'District heating'), ('wood_central_heating', 'Wood central heating'), ('fireplace', 'Fireplace'), ('convectors', 'Convectors')], max_length=256, null=True, verbose_name='Heating source'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='heating_source',
            field=models.CharField(blank=True, choices=[('central_heating', 'Central heating in building'), ('individual_central_heating', 'Individual central heating'), ('underfloor_heating', 'Underfloor heating'), ('district_heating', 'District heating'), ('wood_central_heating', 'Wood central heating'), ('fireplace', 'Fireplace'), ('convectors', 'Convectors')], max_length=256, null=True, verbose_name='Heating source'),
        ),
    ]
