# Generated by Django 3.1 on 2021-02-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0079_auto_20210214_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='promote_site',
        ),
        migrations.RemoveField(
            model_name='property',
            name='promote_site_homepage',
        ),
        migrations.RemoveField(
            model_name='property',
            name='promoted',
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='orientation',
            field=models.CharField(blank=True, choices=[('north', 'North'), ('northeast', 'Northeast'), ('east', 'East'), ('southeast', 'Southeast'), ('south', 'South'), ('southwest', 'Southwest'), ('west', 'West'), ('northwest', 'Northwest'), ('northsouth', 'Northsouth'), ('eastwest', 'Eastwest')], max_length=50, null=True, verbose_name='Orientation'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='orientation',
            field=models.CharField(blank=True, choices=[('north', 'North'), ('northeast', 'Northeast'), ('east', 'East'), ('southeast', 'Southeast'), ('south', 'South'), ('southwest', 'Southwest'), ('west', 'West'), ('northwest', 'Northwest'), ('northsouth', 'Northsouth'), ('eastwest', 'Eastwest')], max_length=50, null=True, verbose_name='Orientation'),
        ),
        migrations.AlterField(
            model_name='hotelattributes',
            name='orientation',
            field=models.CharField(blank=True, choices=[('north', 'North'), ('northeast', 'Northeast'), ('east', 'East'), ('southeast', 'Southeast'), ('south', 'South'), ('southwest', 'Southwest'), ('west', 'West'), ('northwest', 'Northwest'), ('northsouth', 'Northsouth'), ('eastwest', 'Eastwest')], max_length=50, null=True, verbose_name='Orientation'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='orientation',
            field=models.CharField(blank=True, choices=[('north', 'North'), ('northeast', 'Northeast'), ('east', 'East'), ('southeast', 'Southeast'), ('south', 'South'), ('southwest', 'Southwest'), ('west', 'West'), ('northwest', 'Northwest'), ('northsouth', 'Northsouth'), ('eastwest', 'Eastwest')], max_length=50, null=True, verbose_name='Orientation'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='orientation',
            field=models.CharField(blank=True, choices=[('north', 'North'), ('northeast', 'Northeast'), ('east', 'East'), ('southeast', 'Southeast'), ('south', 'South'), ('southwest', 'Southwest'), ('west', 'West'), ('northwest', 'Northwest'), ('northsouth', 'Northsouth'), ('eastwest', 'Eastwest')], max_length=50, null=True, verbose_name='Orientation'),
        ),
    ]
