# Generated by Django 3.1 on 2021-03-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0083_add_property_subtypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinattributes',
            name='subtype',
            field=models.CharField(blank=True, choices=[('cabin', 'cabin')], max_length=50, null=True, verbose_name='Cabin subtype'),
        ),
    ]
