# Generated by Django 3.1 on 2021-03-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0084_cabinattributes_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front line m'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface built m2'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface field m2'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface total m2'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface util m2'),
        ),
        migrations.AlterField(
            model_name='cabinattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front line m'),
        ),
        migrations.AlterField(
            model_name='cabinattributes',
            name='subtype',
            field=models.CharField(blank=True, choices=[('cabin', 'Cabin')], max_length=50, null=True, verbose_name='Cabin subtype'),
        ),
        migrations.AlterField(
            model_name='cabinattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface built m2'),
        ),
        migrations.AlterField(
            model_name='cabinattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface field m2'),
        ),
        migrations.AlterField(
            model_name='cabinattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface total m2'),
        ),
        migrations.AlterField(
            model_name='cabinattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface util m2'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front line m'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface built m2'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface field m2'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface total m2'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface util m2'),
        ),
        migrations.AlterField(
            model_name='hotelattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front line m'),
        ),
        migrations.AlterField(
            model_name='hotelattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface built m2'),
        ),
        migrations.AlterField(
            model_name='hotelattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface field m2'),
        ),
        migrations.AlterField(
            model_name='hotelattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface total m2'),
        ),
        migrations.AlterField(
            model_name='hotelattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface util m2'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front line m'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface built m2'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface field m2'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface total m2'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface util m2'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front line m'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='subtype',
            field=models.CharField(blank=True, choices=[('agricultural_land', 'Agricultural land'), ('construction_land', 'Construction land')], max_length=50, null=True, verbose_name='Land subtype'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface built m2'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface field m2'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface total m2'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface util m2'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front line m'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface built m2'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface field m2'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface total m2'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface util m2'),
        ),
    ]
