# Generated by Django 3.1 on 2021-03-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0085_auto_20210304_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='public',
        ),
    ]
