# Generated by Django 3.1 on 2021-03-13 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0086_remove_propertyimage_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentattributes',
            name='description_sentimental',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Description sentimental'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='garage',
            field=models.CharField(blank=True, choices=[('garage', 'Garage'), ('underground_garage', 'Underground parking'), ('exterior_parking', 'Exterior parking'), ('subscription_parking', 'Subscription parking')], max_length=256, null=True, verbose_name='Parking'),
        ),
        migrations.AlterField(
            model_name='cabinattributes',
            name='description_sentimental',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Description sentimental'),
        ),
        migrations.AlterField(
            model_name='cabinattributes',
            name='garage',
            field=models.CharField(blank=True, choices=[('garage', 'Garage'), ('underground_garage', 'Underground parking'), ('exterior_parking', 'Exterior parking'), ('subscription_parking', 'Subscription parking')], max_length=256, null=True, verbose_name='Parking'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='description_sentimental',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Description sentimental'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='garage',
            field=models.CharField(blank=True, choices=[('garage', 'Garage'), ('underground_garage', 'Underground parking'), ('exterior_parking', 'Exterior parking'), ('subscription_parking', 'Subscription parking')], max_length=256, null=True, verbose_name='Parking'),
        ),
        migrations.AlterField(
            model_name='hotelattributes',
            name='description_sentimental',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Description sentimental'),
        ),
        migrations.AlterField(
            model_name='hotelattributes',
            name='garage',
            field=models.CharField(blank=True, choices=[('garage', 'Garage'), ('underground_garage', 'Underground parking'), ('exterior_parking', 'Exterior parking'), ('subscription_parking', 'Subscription parking')], max_length=256, null=True, verbose_name='Parking'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='description_sentimental',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Description sentimental'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='garage',
            field=models.CharField(blank=True, choices=[('garage', 'Garage'), ('underground_garage', 'Underground parking'), ('exterior_parking', 'Exterior parking'), ('subscription_parking', 'Subscription parking')], max_length=256, null=True, verbose_name='Parking'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='description_sentimental',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Description sentimental'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='description_sentimental',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Description sentimental'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='garage',
            field=models.CharField(blank=True, choices=[('garage', 'Garage'), ('underground_garage', 'Underground parking'), ('exterior_parking', 'Exterior parking'), ('subscription_parking', 'Subscription parking')], max_length=256, null=True, verbose_name='Parking'),
        ),
    ]
