# Generated by Django 3.1 on 2021-03-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0087_auto_20210313_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialattributes',
            name='window_shop',
            field=models.BooleanField(default=False, verbose_name='Window shop'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='comfort',
            field=models.CharField(blank=True, choices=[('increased', 'Increased'), ('one', 'One'), ('unique', 'Unique'), ('two', 'Two'), ('three', 'Three')], max_length=50, null=True, verbose_name='Comfort'),
        ),
        migrations.AlterField(
            model_name='cabinattributes',
            name='comfort',
            field=models.CharField(blank=True, choices=[('increased', 'Increased'), ('one', 'One'), ('unique', 'Unique'), ('two', 'Two'), ('three', 'Three')], max_length=50, null=True, verbose_name='Comfort'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='comfort',
            field=models.CharField(blank=True, choices=[('increased', 'Increased'), ('one', 'One'), ('unique', 'Unique'), ('two', 'Two'), ('three', 'Three')], max_length=50, null=True, verbose_name='Comfort'),
        ),
        migrations.AlterField(
            model_name='hotelattributes',
            name='comfort',
            field=models.CharField(blank=True, choices=[('increased', 'Increased'), ('one', 'One'), ('unique', 'Unique'), ('two', 'Two'), ('three', 'Three')], max_length=50, null=True, verbose_name='Comfort'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='comfort',
            field=models.CharField(blank=True, choices=[('increased', 'Increased'), ('one', 'One'), ('unique', 'Unique'), ('two', 'Two'), ('three', 'Three')], max_length=50, null=True, verbose_name='Comfort'),
        ),
        migrations.AlterField(
            model_name='property',
            name='floor',
            field=models.CharField(blank=True, choices=[('basement', 'Basement'), ('semi_basement', 'Semi Basement'), ('ground_floor', 'Ground Floor'), ('entresol_floor', 'Entresol'), ('mansard', 'Mansard'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=20, null=True, verbose_name='Floor'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='comfort',
            field=models.CharField(blank=True, choices=[('increased', 'Increased'), ('one', 'One'), ('unique', 'Unique'), ('two', 'Two'), ('three', 'Three')], max_length=50, null=True, verbose_name='Comfort'),
        ),
    ]
