# Generated by Django 3.1 on 2021-04-03 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0091_auto_20210401_0746'),
        ('properties', '0091_auto_20210403_1545'),
    ]

    operations = [
    ]
