# Generated by Django 3.1 on 2021-04-12 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0093_latitude_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('document_path', models.CharField(max_length=255, verbose_name='Image path')),
                ('document_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Image name')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property', verbose_name='Property')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
