# Generated by Django 3.1 on 2021-07-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0044_demand_offers_of_interest'),
        ('properties', '0094_propertydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='demands_of_interest',
            field=models.ManyToManyField(blank=True, to='demands.Demand', verbose_name='Demands of interest'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='built',
            field=models.CharField(blank=True, choices=[('before_1960', 'Before 1960'), ('between_1960_2010', 'Between 1960 - 2010'), ('after_2010', 'After 2010')], max_length=256, null=True, verbose_name='Built'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='construction_material',
            field=models.CharField(blank=True, choices=[('brick', 'Brick'), ('concrete', 'Concrete'), ('bca', 'BCA'), ('wood', 'Wood'), ('limestone', 'Limestone')], max_length=50, null=True, verbose_name='Construction material'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='interior_state',
            field=models.CharField(blank=True, choices=[('in white', 'In white'), ('in grey', 'In grey'), ('with fixes', 'With fixes'), ('unfinished', 'Unfinished'), ('lux', 'Luxurious')], max_length=50, null=True, verbose_name='Interior state'),
        ),
        migrations.AlterField(
            model_name='cabinattributes',
            name='built',
            field=models.CharField(blank=True, choices=[('before_1960', 'Before 1960'), ('between_1960_2010', 'Between 1960 - 2010'), ('after_2010', 'After 2010')], max_length=256, null=True, verbose_name='Built'),
        ),
        migrations.AlterField(
            model_name='cabinattributes',
            name='construction_material',
            field=models.CharField(blank=True, choices=[('brick', 'Brick'), ('concrete', 'Concrete'), ('bca', 'BCA'), ('wood', 'Wood'), ('limestone', 'Limestone')], max_length=50, null=True, verbose_name='Construction material'),
        ),
        migrations.AlterField(
            model_name='cabinattributes',
            name='interior_state',
            field=models.CharField(blank=True, choices=[('in white', 'In white'), ('in grey', 'In grey'), ('with fixes', 'With fixes'), ('unfinished', 'Unfinished'), ('lux', 'Luxurious')], max_length=50, null=True, verbose_name='Interior state'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='built',
            field=models.CharField(blank=True, choices=[('before_1960', 'Before 1960'), ('between_1960_2010', 'Between 1960 - 2010'), ('after_2010', 'After 2010')], max_length=256, null=True, verbose_name='Built'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='construction_material',
            field=models.CharField(blank=True, choices=[('brick', 'Brick'), ('concrete', 'Concrete'), ('bca', 'BCA'), ('wood', 'Wood'), ('limestone', 'Limestone')], max_length=50, null=True, verbose_name='Construction material'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='interior_state',
            field=models.CharField(blank=True, choices=[('in white', 'In white'), ('in grey', 'In grey'), ('with fixes', 'With fixes'), ('unfinished', 'Unfinished'), ('lux', 'Luxurious')], max_length=50, null=True, verbose_name='Interior state'),
        ),
        migrations.AlterField(
            model_name='hotelattributes',
            name='built',
            field=models.CharField(blank=True, choices=[('before_1960', 'Before 1960'), ('between_1960_2010', 'Between 1960 - 2010'), ('after_2010', 'After 2010')], max_length=256, null=True, verbose_name='Built'),
        ),
        migrations.AlterField(
            model_name='hotelattributes',
            name='construction_material',
            field=models.CharField(blank=True, choices=[('brick', 'Brick'), ('concrete', 'Concrete'), ('bca', 'BCA'), ('wood', 'Wood'), ('limestone', 'Limestone')], max_length=50, null=True, verbose_name='Construction material'),
        ),
        migrations.AlterField(
            model_name='hotelattributes',
            name='interior_state',
            field=models.CharField(blank=True, choices=[('in white', 'In white'), ('in grey', 'In grey'), ('with fixes', 'With fixes'), ('unfinished', 'Unfinished'), ('lux', 'Luxurious')], max_length=50, null=True, verbose_name='Interior state'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='built',
            field=models.CharField(blank=True, choices=[('before_1960', 'Before 1960'), ('between_1960_2010', 'Between 1960 - 2010'), ('after_2010', 'After 2010')], max_length=256, null=True, verbose_name='Built'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='construction_material',
            field=models.CharField(blank=True, choices=[('brick', 'Brick'), ('concrete', 'Concrete'), ('bca', 'BCA'), ('wood', 'Wood'), ('limestone', 'Limestone')], max_length=50, null=True, verbose_name='Construction material'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='interior_state',
            field=models.CharField(blank=True, choices=[('in white', 'In white'), ('in grey', 'In grey'), ('with fixes', 'With fixes'), ('unfinished', 'Unfinished'), ('lux', 'Luxurious')], max_length=50, null=True, verbose_name='Interior state'),
        ),
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.FloatField(blank=True, default=47.02472305395979, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.FloatField(blank=True, default=28.83250530104991, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='built',
            field=models.CharField(blank=True, choices=[('before_1960', 'Before 1960'), ('between_1960_2010', 'Between 1960 - 2010'), ('after_2010', 'After 2010')], max_length=256, null=True, verbose_name='Built'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='construction_material',
            field=models.CharField(blank=True, choices=[('brick', 'Brick'), ('concrete', 'Concrete'), ('bca', 'BCA'), ('wood', 'Wood'), ('limestone', 'Limestone')], max_length=50, null=True, verbose_name='Construction material'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='interior_state',
            field=models.CharField(blank=True, choices=[('in white', 'In white'), ('in grey', 'In grey'), ('with fixes', 'With fixes'), ('unfinished', 'Unfinished'), ('lux', 'Luxurious')], max_length=50, null=True, verbose_name='Interior state'),
        ),
    ]
