# Generated by Django 3.1 on 2021-12-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0096_property_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='conclusion',
            field=models.TextField(blank=True, null=True, verbose_name='Conclusion'),
        ),
    ]
