# Generated by Django 3.1 on 2021-12-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0097_property_conclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='landattributes',
            name='units_of_measure',
            field=models.CharField(blank=True, choices=[('square_meters', 'Square meters'), ('acres', 'Acres'), ('hectares', 'Hectares')], default='square_meters', max_length=50, null=True, verbose_name='Units of measure for land'),
        ),
    ]
