# Generated by Django 3.1 on 2022-01-11 12:59

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0098_landattributes_units_of_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuregroup',
            name='property_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('studio', 'Studio'), ('commercial', 'Commercial space'), ('land', 'Land'), ('hotel', 'Hotel'), ('cabin', 'Cabin'), ('basement_parking', 'Basement Parking'), ('garage', 'Garage'), ('storage_room', 'Storage Room')], max_length=56, null=True, verbose_name='Property type'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='units_of_measure',
            field=models.CharField(blank=True, choices=[('square_meters', 'Square meters'), ('acres', 'Acres'), ('hectares', 'Hectares')], default='square_meters', max_length=50, null=True, verbose_name='Units of measure'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('studio', 'Studio'), ('commercial', 'Commercial space'), ('land', 'Land'), ('hotel', 'Hotel'), ('cabin', 'Cabin'), ('basement_parking', 'Basement Parking'), ('garage', 'Garage'), ('storage_room', 'Storage Room')], db_index=True, max_length=56, null=True, verbose_name='Type'),
        ),
    ]
