# Generated by Django 3.1 on 2022-02-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0101_auto_20220121_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentattributes',
            name='units_of_measure',
            field=models.CharField(blank=True, choices=[('square_meters', 'Square meters'), ('acres', 'Acres'), ('hectares', 'Hectares')], default='square_meters', max_length=50, null=True, verbose_name='Units of measure'),
        ),
        migrations.AddField(
            model_name='basementparkingattributes',
            name='units_of_measure',
            field=models.CharField(blank=True, choices=[('square_meters', 'Square meters'), ('acres', 'Acres'), ('hectares', 'Hectares')], default='square_meters', max_length=50, null=True, verbose_name='Units of measure'),
        ),
        migrations.AddField(
            model_name='cabinattributes',
            name='units_of_measure',
            field=models.CharField(blank=True, choices=[('square_meters', 'Square meters'), ('acres', 'Acres'), ('hectares', 'Hectares')], default='square_meters', max_length=50, null=True, verbose_name='Units of measure'),
        ),
        migrations.AddField(
            model_name='commercialattributes',
            name='units_of_measure',
            field=models.CharField(blank=True, choices=[('square_meters', 'Square meters'), ('acres', 'Acres'), ('hectares', 'Hectares')], default='square_meters', max_length=50, null=True, verbose_name='Units of measure'),
        ),
        migrations.AddField(
            model_name='complexattributes',
            name='units_of_measure',
            field=models.CharField(blank=True, choices=[('square_meters', 'Square meters'), ('acres', 'Acres'), ('hectares', 'Hectares')], default='square_meters', max_length=50, null=True, verbose_name='Units of measure'),
        ),
        migrations.AddField(
            model_name='garageattributes',
            name='units_of_measure',
            field=models.CharField(blank=True, choices=[('square_meters', 'Square meters'), ('acres', 'Acres'), ('hectares', 'Hectares')], default='square_meters', max_length=50, null=True, verbose_name='Units of measure'),
        ),
        migrations.AddField(
            model_name='hotelattributes',
            name='units_of_measure',
            field=models.CharField(blank=True, choices=[('square_meters', 'Square meters'), ('acres', 'Acres'), ('hectares', 'Hectares')], default='square_meters', max_length=50, null=True, verbose_name='Units of measure'),
        ),
        migrations.AddField(
            model_name='houseattributes',
            name='units_of_measure',
            field=models.CharField(blank=True, choices=[('square_meters', 'Square meters'), ('acres', 'Acres'), ('hectares', 'Hectares')], default='square_meters', max_length=50, null=True, verbose_name='Units of measure'),
        ),
        migrations.AddField(
            model_name='storageroomattributes',
            name='units_of_measure',
            field=models.CharField(blank=True, choices=[('square_meters', 'Square meters'), ('acres', 'Acres'), ('hectares', 'Hectares')], default='square_meters', max_length=50, null=True, verbose_name='Units of measure'),
        ),
        migrations.AddField(
            model_name='studioattributes',
            name='units_of_measure',
            field=models.CharField(blank=True, choices=[('square_meters', 'Square meters'), ('acres', 'Acres'), ('hectares', 'Hectares')], default='square_meters', max_length=50, null=True, verbose_name='Units of measure'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front line'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface built'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface field'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_garden',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface garden'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface total'),
        ),
        migrations.AlterField(
            model_name='apartmentattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface util'),
        ),
        migrations.AlterField(
            model_name='basementparkingattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front line'),
        ),
        migrations.AlterField(
            model_name='basementparkingattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface built'),
        ),
        migrations.AlterField(
            model_name='basementparkingattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface field'),
        ),
        migrations.AlterField(
            model_name='basementparkingattributes',
            name='surface_garden',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface garden'),
        ),
        migrations.AlterField(
            model_name='basementparkingattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface total'),
        ),
        migrations.AlterField(
            model_name='basementparkingattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface util'),
        ),
        migrations.AlterField(
            model_name='cabinattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front line'),
        ),
        migrations.AlterField(
            model_name='cabinattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface built'),
        ),
        migrations.AlterField(
            model_name='cabinattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface field'),
        ),
        migrations.AlterField(
            model_name='cabinattributes',
            name='surface_garden',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface garden'),
        ),
        migrations.AlterField(
            model_name='cabinattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface total'),
        ),
        migrations.AlterField(
            model_name='cabinattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface util'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front line'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface built'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface field'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_garden',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface garden'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface total'),
        ),
        migrations.AlterField(
            model_name='commercialattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface util'),
        ),
        migrations.AlterField(
            model_name='complexattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front line'),
        ),
        migrations.AlterField(
            model_name='complexattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface built'),
        ),
        migrations.AlterField(
            model_name='complexattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface field'),
        ),
        migrations.AlterField(
            model_name='complexattributes',
            name='surface_garden',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface garden'),
        ),
        migrations.AlterField(
            model_name='complexattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface total'),
        ),
        migrations.AlterField(
            model_name='complexattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface util'),
        ),
        migrations.AlterField(
            model_name='garageattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front line'),
        ),
        migrations.AlterField(
            model_name='garageattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface built'),
        ),
        migrations.AlterField(
            model_name='garageattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface field'),
        ),
        migrations.AlterField(
            model_name='garageattributes',
            name='surface_garden',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface garden'),
        ),
        migrations.AlterField(
            model_name='garageattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface total'),
        ),
        migrations.AlterField(
            model_name='garageattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface util'),
        ),
        migrations.AlterField(
            model_name='hotelattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front line'),
        ),
        migrations.AlterField(
            model_name='hotelattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface built'),
        ),
        migrations.AlterField(
            model_name='hotelattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface field'),
        ),
        migrations.AlterField(
            model_name='hotelattributes',
            name='surface_garden',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface garden'),
        ),
        migrations.AlterField(
            model_name='hotelattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface total'),
        ),
        migrations.AlterField(
            model_name='hotelattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface util'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front line'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface built'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface field'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_garden',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface garden'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface total'),
        ),
        migrations.AlterField(
            model_name='houseattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface util'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front line'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface built'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface field'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_garden',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface garden'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface total'),
        ),
        migrations.AlterField(
            model_name='landattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface util'),
        ),
        migrations.AlterField(
            model_name='storageroomattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front line'),
        ),
        migrations.AlterField(
            model_name='storageroomattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface built'),
        ),
        migrations.AlterField(
            model_name='storageroomattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface field'),
        ),
        migrations.AlterField(
            model_name='storageroomattributes',
            name='surface_garden',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface garden'),
        ),
        migrations.AlterField(
            model_name='storageroomattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface total'),
        ),
        migrations.AlterField(
            model_name='storageroomattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface util'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='front_line',
            field=models.FloatField(blank=True, null=True, verbose_name='Front line'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_built',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface built'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_field',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface field'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_garden',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface garden'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_total',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface total'),
        ),
        migrations.AlterField(
            model_name='studioattributes',
            name='surface_util',
            field=models.FloatField(blank=True, null=True, verbose_name='Surface util'),
        ),
    ]
