# Generated by Django 3.1 on 2022-02-10 14:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0102_auto_20220207_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuregroup',
            name='property_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('studio', 'Studio'), ('commercial', 'Commercial space'), ('land', 'Land'), ('hotel', 'Hotel'), ('cabin', 'Cabin'), ('complex', 'Complex'), ('basement_parking', 'Basement Parking'), ('garage', 'Garage'), ('storage_room', 'Storage Room')], max_length=200, null=True, verbose_name='Property type'),
        ),
    ]
