# Generated by Django 3.1 on 2022-02-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0103_auto_20220210_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rex_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rex Property ID'),
        ),
    ]
