# Generated by Django 3.1 on 2022-02-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0104_property_rex_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='report_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Report end date'),
        ),
        migrations.AddField(
            model_name='property',
            name='report_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Report start date'),
        ),
    ]
