# Generated by Django 3.1 on 2022-02-18 19:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0105_auto_20220216_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='external_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=50, null=True),
        ),
    ]
