# Generated by Django 3.1 on 2022-02-21 12:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0106_property_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='rex_id',
        ),
        migrations.AlterField(
            model_name='property',
            name='external_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=50, null=True, verbose_name='Property External ID'),
        ),
    ]
