# Generated by Django 3.1 on 2022-03-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0108_auto_20220225_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentattributes',
            name='description_english',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description in english'),
        ),
        migrations.AddField(
            model_name='basementparkingattributes',
            name='description_english',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description in english'),
        ),
        migrations.AddField(
            model_name='cabinattributes',
            name='description_english',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description in english'),
        ),
        migrations.AddField(
            model_name='commercialattributes',
            name='description_english',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description in english'),
        ),
        migrations.AddField(
            model_name='complexattributes',
            name='description_english',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description in english'),
        ),
        migrations.AddField(
            model_name='garageattributes',
            name='description_english',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description in english'),
        ),
        migrations.AddField(
            model_name='hotelattributes',
            name='description_english',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description in english'),
        ),
        migrations.AddField(
            model_name='houseattributes',
            name='description_english',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description in english'),
        ),
        migrations.AddField(
            model_name='landattributes',
            name='description_english',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description in english'),
        ),
        migrations.AddField(
            model_name='storageroomattributes',
            name='description_english',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description in english'),
        ),
        migrations.AddField(
            model_name='studioattributes',
            name='description_english',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description in english'),
        ),
    ]
