# Generated by Django 3.1 on 2022-03-28 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0110_auto_20220316_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='rex_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rex Image ID'),
        ),
    ]
