# Generated by Django 3.1 on 2022-04-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0111_propertyimage_rex_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='rex_second_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rex Image Second ID'),
        ),
    ]
