# Generated by Django 3.1 on 2022-04-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0112_propertyimage_rex_second_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyimage',
            name='rex_second_id',
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='rex_ids',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
