# Generated by Django 3.1 on 2022-06-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0114_auto_20220523_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentattributes',
            name='building_plan',
            field=models.CharField(blank=True, choices=[('102', '102'), ('135', '135'), ('143', '143'), ('gostinca', 'Ap. "Gostinka"'), ('brejnevka', 'Brj (Brejnevka)'), ('camin_familial', 'Cămin familial'), ('ceska', 'Cş (Ceşka)'), ('hrusciovka', 'Hruşciovka'), ('individuala', 'Individuală'), ('ms_serie_moldoveneasca', 'Ms (serie  moldovenească)'), ('pe_pamant', 'Pe pămănt'), ('rubaska', 'Rubaşka'), ('stalinka', 'St (Stalinka)'), ('vart', 'Varț (Varnițkaia)')], max_length=30, null=True, verbose_name='Building Plan'),
        ),
    ]
