# Generated by Django 3.1 on 2022-06-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0115_apartmentattributes_building_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentattributes',
            name='rental_fund',
            field=models.CharField(blank=True, choices=[('new_construction', 'Construcţii noi'), ('secondary', 'Secundar')], max_length=20, null=True, verbose_name='Rental Fund'),
        ),
    ]
