# Generated by Django 3.1 on 2022-06-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0117_auto_20220612_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentattributes',
            name='apartment_state',
            field=models.CharField(blank=True, choices=[('in_white', 'In white'), ('in_grey', 'In grey'), ('euro_reparation', 'Euro reparation'), ('individual_design', 'Individual design'), ('without_reparation', 'Without reparation'), ('ready_for_use', 'Ready for use'), ('unfinished_construction', 'Unfinished Construction'), ('need_reparation', 'Need Reparation'), ('cosmetic_reparation', 'Cosmetic Reparation'), ('demolition_house', 'Demolition House')], max_length=30, null=True, verbose_name='Apartment State'),
        ),
    ]
