# Generated by Django 3.1 on 2022-09-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0118_apartmentattributes_apartment_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialattributes',
            name='commercial_state',
            field=models.CharField(blank=True, choices=[('individual_design', 'Individual design'), ('euro_reparation', 'Euro reparation'), ('without_reparation', 'Without reparation'), ('in_white', 'In white'), ('in_grey', 'In grey'), ('need_reparation', 'Need Reparation'), ('cosmetic_reparation', 'Cosmetic Reparation')], max_length=30, null=True, verbose_name='Commercial State'),
        ),
        migrations.AddField(
            model_name='houseattributes',
            name='house_state',
            field=models.CharField(blank=True, choices=[('individual_design', 'Individual design'), ('without_reparation', 'Without reparation'), ('demolition_house', 'Demolition House'), ('unfinished_construction', 'Unfinished Construction'), ('need_reparation', 'Need Reparation'), ('in_grey', 'In grey'), ('in_white', 'In white'), ('cosmetic_reparation', 'Cosmetic Reparation'), ('euro_reparation', 'Euro reparation'), ('ready_for_use', 'Ready for use')], max_length=30, null=True, verbose_name='House State'),
        ),
    ]
