# Generated by Django 3.1 on 2022-09-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0119_auto_20220905_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentattributes',
            name='apartment_construction_material',
            field=models.CharField(blank=True, choices=[('concrete', 'Concrete'), ('bca', 'BCA'), ('blocks', 'Blocks'), ('combined', 'Combined'), ('limestone', 'Limestone'), ('brick', 'Brick'), ('wood', 'Wood'), ('monolith', 'Monolith'), ('panels', 'Panels')], max_length=30, null=True, verbose_name='Construction material'),
        ),
        migrations.AddField(
            model_name='houseattributes',
            name='house_construction_material',
            field=models.CharField(blank=True, choices=[('panels', 'Panels'), ('limestone', 'Limestone'), ('brick', 'Brick'), ('blocks', 'Blocks'), ('monolith', 'Monolith'), ('concrete', 'Concrete'), ('combined', 'Combined'), ('bca', 'BCA'), ('wood', 'Wood'), ('other', 'Other')], max_length=30, null=True, verbose_name='Construction material'),
        ),
    ]
