# Generated by Django 3.1 on 2022-12-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0120_auto_20220905_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentattributes',
            name='gasification',
            field=models.CharField(blank=True, choices=[('gasified', 'Gasified'), ('not_gasified', 'Not gasified')], max_length=50, null=True, verbose_name='Gasification'),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='sewerage',
            field=models.CharField(blank=True, choices=[('without_sewerage', 'Without sewerage'), ('there_sewer', 'There is a sewer')], max_length=50, null=True, verbose_name='Sewerage'),
        ),
        migrations.AddField(
            model_name='apartmentattributes',
            name='water_pipes',
            field=models.CharField(blank=True, choices=[('without_plumbing', 'Without plumbing'), ('there_running_water', 'There is running water')], max_length=50, null=True, verbose_name='Water pipes'),
        ),
        migrations.AddField(
            model_name='basementparkingattributes',
            name='gasification',
            field=models.CharField(blank=True, choices=[('gasified', 'Gasified'), ('not_gasified', 'Not gasified')], max_length=50, null=True, verbose_name='Gasification'),
        ),
        migrations.AddField(
            model_name='basementparkingattributes',
            name='sewerage',
            field=models.CharField(blank=True, choices=[('without_sewerage', 'Without sewerage'), ('there_sewer', 'There is a sewer')], max_length=50, null=True, verbose_name='Sewerage'),
        ),
        migrations.AddField(
            model_name='basementparkingattributes',
            name='water_pipes',
            field=models.CharField(blank=True, choices=[('without_plumbing', 'Without plumbing'), ('there_running_water', 'There is running water')], max_length=50, null=True, verbose_name='Water pipes'),
        ),
        migrations.AddField(
            model_name='cabinattributes',
            name='gasification',
            field=models.CharField(blank=True, choices=[('gasified', 'Gasified'), ('not_gasified', 'Not gasified')], max_length=50, null=True, verbose_name='Gasification'),
        ),
        migrations.AddField(
            model_name='cabinattributes',
            name='sewerage',
            field=models.CharField(blank=True, choices=[('without_sewerage', 'Without sewerage'), ('there_sewer', 'There is a sewer')], max_length=50, null=True, verbose_name='Sewerage'),
        ),
        migrations.AddField(
            model_name='cabinattributes',
            name='water_pipes',
            field=models.CharField(blank=True, choices=[('without_plumbing', 'Without plumbing'), ('there_running_water', 'There is running water')], max_length=50, null=True, verbose_name='Water pipes'),
        ),
        migrations.AddField(
            model_name='commercialattributes',
            name='gasification',
            field=models.CharField(blank=True, choices=[('gasified', 'Gasified'), ('not_gasified', 'Not gasified')], max_length=50, null=True, verbose_name='Gasification'),
        ),
        migrations.AddField(
            model_name='commercialattributes',
            name='sewerage',
            field=models.CharField(blank=True, choices=[('without_sewerage', 'Without sewerage'), ('there_sewer', 'There is a sewer')], max_length=50, null=True, verbose_name='Sewerage'),
        ),
        migrations.AddField(
            model_name='commercialattributes',
            name='water_pipes',
            field=models.CharField(blank=True, choices=[('without_plumbing', 'Without plumbing'), ('there_running_water', 'There is running water')], max_length=50, null=True, verbose_name='Water pipes'),
        ),
        migrations.AddField(
            model_name='complexattributes',
            name='gasification',
            field=models.CharField(blank=True, choices=[('gasified', 'Gasified'), ('not_gasified', 'Not gasified')], max_length=50, null=True, verbose_name='Gasification'),
        ),
        migrations.AddField(
            model_name='complexattributes',
            name='sewerage',
            field=models.CharField(blank=True, choices=[('without_sewerage', 'Without sewerage'), ('there_sewer', 'There is a sewer')], max_length=50, null=True, verbose_name='Sewerage'),
        ),
        migrations.AddField(
            model_name='complexattributes',
            name='water_pipes',
            field=models.CharField(blank=True, choices=[('without_plumbing', 'Without plumbing'), ('there_running_water', 'There is running water')], max_length=50, null=True, verbose_name='Water pipes'),
        ),
        migrations.AddField(
            model_name='garageattributes',
            name='gasification',
            field=models.CharField(blank=True, choices=[('gasified', 'Gasified'), ('not_gasified', 'Not gasified')], max_length=50, null=True, verbose_name='Gasification'),
        ),
        migrations.AddField(
            model_name='garageattributes',
            name='sewerage',
            field=models.CharField(blank=True, choices=[('without_sewerage', 'Without sewerage'), ('there_sewer', 'There is a sewer')], max_length=50, null=True, verbose_name='Sewerage'),
        ),
        migrations.AddField(
            model_name='garageattributes',
            name='water_pipes',
            field=models.CharField(blank=True, choices=[('without_plumbing', 'Without plumbing'), ('there_running_water', 'There is running water')], max_length=50, null=True, verbose_name='Water pipes'),
        ),
        migrations.AddField(
            model_name='hotelattributes',
            name='gasification',
            field=models.CharField(blank=True, choices=[('gasified', 'Gasified'), ('not_gasified', 'Not gasified')], max_length=50, null=True, verbose_name='Gasification'),
        ),
        migrations.AddField(
            model_name='hotelattributes',
            name='sewerage',
            field=models.CharField(blank=True, choices=[('without_sewerage', 'Without sewerage'), ('there_sewer', 'There is a sewer')], max_length=50, null=True, verbose_name='Sewerage'),
        ),
        migrations.AddField(
            model_name='hotelattributes',
            name='water_pipes',
            field=models.CharField(blank=True, choices=[('without_plumbing', 'Without plumbing'), ('there_running_water', 'There is running water')], max_length=50, null=True, verbose_name='Water pipes'),
        ),
        migrations.AddField(
            model_name='houseattributes',
            name='gasification',
            field=models.CharField(blank=True, choices=[('gasified', 'Gasified'), ('not_gasified', 'Not gasified')], max_length=50, null=True, verbose_name='Gasification'),
        ),
        migrations.AddField(
            model_name='houseattributes',
            name='sewerage',
            field=models.CharField(blank=True, choices=[('without_sewerage', 'Without sewerage'), ('there_sewer', 'There is a sewer')], max_length=50, null=True, verbose_name='Sewerage'),
        ),
        migrations.AddField(
            model_name='houseattributes',
            name='water_pipes',
            field=models.CharField(blank=True, choices=[('without_plumbing', 'Without plumbing'), ('there_running_water', 'There is running water')], max_length=50, null=True, verbose_name='Water pipes'),
        ),
        migrations.AddField(
            model_name='storageroomattributes',
            name='gasification',
            field=models.CharField(blank=True, choices=[('gasified', 'Gasified'), ('not_gasified', 'Not gasified')], max_length=50, null=True, verbose_name='Gasification'),
        ),
        migrations.AddField(
            model_name='storageroomattributes',
            name='sewerage',
            field=models.CharField(blank=True, choices=[('without_sewerage', 'Without sewerage'), ('there_sewer', 'There is a sewer')], max_length=50, null=True, verbose_name='Sewerage'),
        ),
        migrations.AddField(
            model_name='storageroomattributes',
            name='water_pipes',
            field=models.CharField(blank=True, choices=[('without_plumbing', 'Without plumbing'), ('there_running_water', 'There is running water')], max_length=50, null=True, verbose_name='Water pipes'),
        ),
        migrations.AddField(
            model_name='studioattributes',
            name='gasification',
            field=models.CharField(blank=True, choices=[('gasified', 'Gasified'), ('not_gasified', 'Not gasified')], max_length=50, null=True, verbose_name='Gasification'),
        ),
        migrations.AddField(
            model_name='studioattributes',
            name='sewerage',
            field=models.CharField(blank=True, choices=[('without_sewerage', 'Without sewerage'), ('there_sewer', 'There is a sewer')], max_length=50, null=True, verbose_name='Sewerage'),
        ),
        migrations.AddField(
            model_name='studioattributes',
            name='water_pipes',
            field=models.CharField(blank=True, choices=[('without_plumbing', 'Without plumbing'), ('there_running_water', 'There is running water')], max_length=50, null=True, verbose_name='Water pipes'),
        ),
    ]
