# Generated by Django 3.1 on 2020-09-29 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0031_auto_20200929_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('sale', 'Sale'), ('rent', 'Rent')], max_length=56, null=True)),
                ('contract_number', models.CharField(blank=True, max_length=70)),
                ('contract_type', models.CharField(blank=True, max_length=70)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('price_minimum', models.IntegerField(blank=True, null=True)),
                ('price_per_sqm', models.IntegerField(blank=True, null=True)),
                ('exclusive', models.BooleanField(default=False)),
                ('special_offer', models.BooleanField(default=False)),
                ('contract_start_date', models.DateField(null=True)),
                ('contract_end_date', models.DateField(null=True)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='properties.property')),
            ],
        ),
    ]
