# Generated by Django 3.1 on 2020-11-09 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0047_auto_20201104_2207'),
        ('offers', '0003_auto_20201007_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='contract_end_date',
            field=models.DateField(null=True, verbose_name='Contract End Date'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='contract_number',
            field=models.CharField(blank=True, max_length=70, verbose_name='Contract Number'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='contract_start_date',
            field=models.DateField(null=True, verbose_name='Contract Start Date'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='contract_type',
            field=models.CharField(blank=True, max_length=70, verbose_name='Contract Type'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='exclusive',
            field=models.BooleanField(default=False, verbose_name='Exclusive'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price_minimum',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price minimum'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price_per_sqm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price Per sqm'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='properties.property', verbose_name='Property'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='special_offer',
            field=models.BooleanField(default=False, verbose_name='Special Offer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=56, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
