# Generated by Django 3.1 on 2020-11-26 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_auto_20201126_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='commission',
            field=models.IntegerField(blank=True, null=True, verbose_name='Commission'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='commission_percent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Commission %'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='final_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Final Price'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='is_transacted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is Transacted'),
        ),
    ]
