# Generated by Django 3.1 on 2020-11-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_auto_20201126_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='is_transacted',
            field=models.BooleanField(default=False, verbose_name='Is Transacted'),
        ),
    ]
