# Generated by Django 3.1 on 2020-11-27 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0004_auto_20201106_1534'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0008_auto_20201126_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='offices.office', verbose_name='Office'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to=settings.AUTH_USER_MODEL, verbose_name='Agent'),
        ),
    ]
