# Generated by Django 3.1 on 2020-12-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_auto_20201127_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='Special Offer'),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_special_offer',
            field=models.BooleanField(default=False, verbose_name='Special Offer'),
        ),
    ]
