# Generated by Django 3.1 on 2020-12-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_auto_20201208_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='is_special_offer',
            new_name='homepage',
        ),
    ]
