# Generated by Django 3.1 on 2020-12-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_auto_20201208_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='homepage',
            field=models.BooleanField(default=False, verbose_name='Homepage'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='Recommended'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Offer Price'),
        ),
    ]
