# Generated by Django 3.1 on 2020-12-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_auto_20201209_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Is Processed'),
        ),
    ]
