# Generated by Django 3.1 on 2020-12-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_offer_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='processed_by',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Processed By'),
        ),
    ]
