# Generated by Django 3.1 on 2021-01-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0014_offer_processed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Process'),
        ),
    ]
