# Generated by Django 3.1 on 2021-01-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0015_auto_20210102_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='contract_end_date',
            field=models.DateField(null=True, verbose_name='Contract end date'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='contract_number',
            field=models.CharField(blank=True, max_length=70, verbose_name='Contract number'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='contract_start_date',
            field=models.DateField(null=True, verbose_name='Contract start date'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='contract_type',
            field=models.CharField(blank=True, max_length=70, verbose_name='Contract type'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='final_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Final price'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='is_transacted',
            field=models.BooleanField(default=False, verbose_name='Is transacted'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price_per_sqm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price per m2'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='processed_by',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Processed by'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='special_offer',
            field=models.BooleanField(default=False, verbose_name='Special offer'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
