# Generated by Django 3.1 on 2021-01-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0017_auto_20210103_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='processed_by',
        ),
        migrations.AddField(
            model_name='offer',
            name='closed_by',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='closed by'),
        ),
    ]
