# Generated by Django 3.1 on 2021-01-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0018_auto_20210103_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='closed_by',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Closed by'),
        ),
    ]
