# Generated by Django 3.1 on 2021-01-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0019_auto_20210103_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='view_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='View Count'),
        ),
    ]
