# Generated by Django 3.1 on 2021-01-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0020_offer_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='view_count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='View Count'),
        ),
    ]
