# Generated by Django 3.1 on 2021-01-26 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0023_auto_20210120_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='contract_number',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='contract_type',
        ),
    ]
