# Generated by Django 3.1 on 2021-01-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0024_auto_20210126_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='commission_percent',
            field=models.FloatField(blank=True, choices=[(4.0, 4.0), (3.5, 3.5), (3.0, 3.0), (2.5, 2.5), (2.0, 2.0), (1.5, 1.5), (1.0, 1.0), (0.5, 0.5)], null=True, verbose_name='Commission %'),
        ),
    ]
