# Generated by Django 3.1 on 2021-01-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0026_auto_20210128_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='VAT',
            field=models.CharField(blank=True, choices=[('included', 'VAT Included'), ('plus_vat', 'Plus VAT')], default='', max_length=56, verbose_name='VAT'),
        ),
    ]
