# Generated by Django 3.1 on 2021-01-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0027_offer_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Close offer'),
        ),
    ]
