# Generated by Django 3.1 on 2021-01-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0028_auto_20210129_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Contract end date'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Contract start date'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.CharField(blank=True, choices=[('sale', 'Sale'), ('exclusive_sale', 'Exclusive sale'), ('rent', 'Rent'), ('exclusive_rent', 'Exclusive rent')], default='sale', max_length=56, null=True, verbose_name='Type'),
        ),
    ]
