# Generated by Django 3.1 on 2021-01-29 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0029_auto_20210129_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='contract_number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)], verbose_name='Contract number'),
        ),
        migrations.AddField(
            model_name='offer',
            name='contract_signing_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Contract signing date'),
        ),
        migrations.AddField(
            model_name='offer',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('sale', 'Sale'), ('exclusive_sale', 'Exclusive sale'), ('rent', 'Rent'), ('exclusive_rent', 'Exclusive rent')], max_length=70, verbose_name='Contract type'),
        ),
    ]
