# Generated by Django 3.1 on 2021-01-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0030_auto_20210129_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='contract_type',
        ),
        migrations.AlterField(
            model_name='offer',
            name='type',
            field=models.CharField(blank=True, choices=[('sale', 'Sale'), ('rent', 'Rent')], default='sale', max_length=56, null=True, verbose_name='Type'),
        ),
    ]
