# Generated by Django 3.1 on 2021-02-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0033_auto_20210214_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='promote_site',
            field=models.BooleanField(default=False, verbose_name='Promote site'),
        ),
        migrations.AddField(
            model_name='offer',
            name='promote_site_homepage',
            field=models.BooleanField(default=False, verbose_name='Promote site homepage'),
        ),
        migrations.AddField(
            model_name='offer',
            name='promoted',
            field=models.BooleanField(default=False, verbose_name='Promoted'),
        ),
    ]
