# Generated by Django 3.1 on 2021-03-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0034_auto_20210215_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='contract_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Contract number'),
        ),
    ]
