# Generated by Django 3.1 on 2021-03-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0035_auto_20210322_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(blank=True, choices=[('incomplete', 'Incomplete'), ('active', 'Active'), ('transacted', 'Transacted by Impakt'), ('transacted_by_others', 'Transacted by others'), ('transacted_by_owner', 'Transacted by owner'), ('withdrawn', 'Withdrawn')], default='incomplete', max_length=50, null=True, verbose_name='Status'),
        ),
    ]
