# Generated by Django 3.1 on 2021-03-25 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0036_auto_20210322_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='is_transacted',
        ),
    ]
