# Generated by Django 3.1 on 2021-03-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0037_remove_offer_is_transacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='contract_register_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Contract register'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='contract_signing_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Contract register'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Contract signing date'),
        ),
    ]
