# Generated by Django 3.1 on 2021-04-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0038_auto_20210325_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='commission_percent',
            field=models.FloatField(blank=True, choices=[(100, 100), (50, 50), (35, 35), (4.0, 4.0), (3.5, 3.5), (3.0, 3.0), (2.5, 2.5), (2.0, 2.0), (1.5, 1.5), (1.0, 1.0), (0.5, 0.5)], null=True, verbose_name='Commission %'),
        ),
    ]
