# Generated by Django 3.1 on 2021-06-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0040_auto_20210403_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='closing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Closing date'),
        ),
    ]
