# Generated by Django 3.1 on 2021-06-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0041_offer_closing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='contract_number',
            field=models.CharField(blank=True, default='', max_length=256, null=True, verbose_name='Contract number'),
        ),
    ]
