# Generated by Django 3.1 on 2021-06-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0045_auto_20210625_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_validated',
            field=models.BooleanField(default=False, verbose_name='Validated'),
        ),
        migrations.AddField(
            model_name='offer',
            name='validation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validation_date'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(blank=True, choices=[('incomplete', 'Incomplete'), ('pending', 'Pending'), ('active', 'Active'), ('reserved', 'Reserved'), ('transacted', 'Transacted by us'), ('transacted_by_others', 'Transacted by others'), ('transacted_by_owner', 'Transacted by owner'), ('withdrawn', 'Withdrawn')], default='incomplete', max_length=50, null=True, verbose_name='Status'),
        ),
    ]
