# Generated by Django 3.1 on 2021-07-01 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0046_auto_20210628_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('title', models.CharField(blank=True, default='', max_length=256, verbose_name='Title')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='Is viewed')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='offers.offer', verbose_name='Offer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
