# Generated by Django 3.1 on 2021-11-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0048_auto_20211026_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='mls_999',
            field=models.BooleanField(default=False, null=True, verbose_name='999.MD'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='mls_remax_global',
            field=models.BooleanField(default=False, null=True, verbose_name='RE/MAX Global'),
        ),
    ]
