# Generated by Django 3.1 on 2022-02-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0049_auto_20211102_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='commission_success',
            field=models.IntegerField(blank=True, null=True, verbose_name='Commission for successful transaction'),
        ),
    ]
