# Generated by Django 3.1 on 2022-02-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0050_offer_commission_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='commission_success',
            field=models.FloatField(blank=True, null=True, verbose_name='Commission for successful transaction'),
        ),
    ]
