# Generated by Django 3.1 on 2022-02-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0051_auto_20220207_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='commission_colaboration',
            field=models.FloatField(blank=True, null=True, verbose_name='Commission for colaboration'),
        ),
    ]
