# Generated by Django 3.1 on 2022-03-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0052_offer_commission_colaboration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='mls_remax_global',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='RE/MAX Global'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='mls_remax_global_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
