# Generated by Django 3.1 on 2022-04-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0054_auto_20220302_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='mls_remax_global_updated',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='RE/MAX Global updated'),
        ),
    ]
