# Generated by Django 3.1 on 2022-04-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0055_offer_mls_remax_global_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='commission_buyer',
            field=models.IntegerField(blank=True, null=True, verbose_name='Commission Buyer'),
        ),
        migrations.AddField(
            model_name='offer',
            name='commission_buyer_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Commission Buyer %'),
        ),
    ]
