# Generated by Django 3.1 on 2022-04-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0056_auto_20220414_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='commission',
            field=models.IntegerField(blank=True, null=True, verbose_name='Commission Seller'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='commission_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Commission Seller %'),
        ),
    ]
