# Generated by Django 3.1 on 2022-04-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0057_auto_20220414_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='mls_remax_global_updated',
        ),
        migrations.AlterField(
            model_name='offer',
            name='mls_999',
            field=models.BooleanField(default=False, verbose_name='999.MD'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='mls_remax_global',
            field=models.BooleanField(default=False, verbose_name='RE/MAX Global'),
        ),
    ]
