# Generated by Django 3.1 on 2022-09-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0061_offer_casahub'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='makler',
            field=models.BooleanField(default=False, verbose_name='Makler.md'),
        ),
    ]
