# Generated by Django 3.1 on 2022-12-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0062_offer_makler'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price_old',
            field=models.IntegerField(blank=True, null=True, verbose_name='Old offer price'),
        ),
    ]
