# Generated by Django 3.1 on 2022-12-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0063_offer_price_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='price_hot',
            field=models.BooleanField(default=False, verbose_name='Hot price'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price_old',
            field=models.IntegerField(blank=True, null=True, verbose_name='Old price'),
        ),
    ]
