# Generated by Django 3.1 on 2020-12-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20201223_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
