# Generated by Django 3.1 on 2021-01-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20201223_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='parent_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
