# Generated by Django 3.1 on 2021-02-13 22:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('audit', '0005_auditlog_parent_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='action_description',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='parent_object_id',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Delete'), ('agent_changed', 'Agent Changed'), ('offer_created', 'Offer Created'), ('offer_updated', 'Offer Updated'), ('attributes_updated', 'Attributes Updated'), ('other', 'Others')], default='other', max_length=256, verbose_name='Action type'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='child_object_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='child_object_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='field_changes',
            field=models.JSONField(blank=True, null=True, verbose_name='Field Changes'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='object_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.PositiveIntegerField(db_index=True, default=2),
            preserve_default=False,
        ),
    ]
