# Generated by Django 3.1 on 2021-02-14 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_auto_20210213_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='deleted_at',
        ),
    ]
