# Generated by Django 3.1 on 2022-02-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integration',
            name='access_key',
        ),
        migrations.AddField(
            model_name='integration',
            name='api_key',
            field=models.CharField(blank=True, default='8B236648-9BEB-4466-A5EA-29491A91D1EF', max_length=100, null=True, verbose_name='API key'),
        ),
        migrations.AddField(
            model_name='integration',
            name='integrator_id',
            field=models.IntegerField(blank=True, default=1056001, null=True, verbose_name='Integrator ID'),
        ),
        migrations.AddField(
            model_name='integration',
            name='region_id',
            field=models.IntegerField(blank=True, default=1056, null=True, verbose_name='Region ID'),
        ),
        migrations.AddField(
            model_name='integration',
            name='secret_key',
            field=models.CharField(blank=True, default='DDD5DA68-9F96-4578-B748-0A49EBEC61F2', max_length=100, null=True, verbose_name='Secret integration key'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Refresh token'),
        ),
    ]
