# Generated by Django 3.1 on 2022-02-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_auto_20220217_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='integrator_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Integrator ID'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Refresh token'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='region_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Region ID'),
        ),
    ]
