# Generated by Django 3.1 on 2022-02-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_auto_20220217_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='api_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='API key'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='secret_key',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Secret integration key'),
        ),
    ]
