# Generated by Django 3.1 on 2020-08-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
