# Generated by Django 3.1 on 2020-09-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0002_office_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
