# Generated by Django 3.1 on 2020-11-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0003_auto_20200928_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='office',
            name='slug',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Slug'),
        ),
    ]
