# Generated by Django 3.1 on 2021-01-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0005_auto_20210103_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Deleted At'),
        ),
    ]
