# Generated by Django 3.1 on 2021-01-03 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0006_office_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255, verbose_name='Image path')),
                ('public', models.BooleanField(default=True, verbose_name='Public')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('position', models.PositiveIntegerField(default=100, verbose_name='Image Position')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='offices.office', verbose_name='Office')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
