# Generated by Django 3.1 on 2021-01-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0007_officeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='office',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is active'),
        ),
        migrations.AddField(
            model_name='office',
            name='show_on_site',
            field=models.BooleanField(default=False, verbose_name='Show on site'),
        ),
    ]
