# Generated by Django 3.1 on 2021-01-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0008_auto_20210104_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='officeimage',
            name='show_on_site',
            field=models.BooleanField(default=True, verbose_name='Show on site'),
        ),
    ]
