# Generated by Django 3.1 on 2021-02-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0011_officeimage_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Deleted'),
        ),
    ]
