# Generated by Django 3.1 on 2022-02-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0015_remove_officeimage_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='rex_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rex Office ID'),
        ),
    ]
