# Generated by Django 3.1 on 2022-02-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0016_office_rex_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='office',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='office',
            name='postal_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Postal code'),
        ),
    ]
