# Generated by Django 3.1 on 2022-02-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0017_auto_20220217_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='External ID'),
        ),
    ]
