# Generated by Django 3.1 on 2022-02-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0018_office_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='international_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='International ID'),
        ),
    ]
