# Generated by Django 3.1 on 2022-02-17 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_auto_20220215_1145'),
        ('offices', '0019_office_international_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='external_id',
        ),
        migrations.AddField(
            model_name='office',
            name='city_gobal_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city', to='locations.city', verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='office',
            name='rex_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Rex Office ID'),
        ),
    ]
