# Generated by Django 3.1 on 2022-02-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0021_auto_20220217_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='office_url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Web Office URL'),
        ),
    ]
