# Generated by Django 3.1 on 2022-02-21 12:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0022_office_office_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='rex_id',
        ),
        migrations.AddField(
            model_name='office',
            name='external_id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=50, null=True, verbose_name='Office external ID'),
        ),
    ]
