# Generated by Django 3.1 on 2022-02-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0023_auto_20220221_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='external_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Office external ID'),
        ),
    ]
