# Generated by Django 3.1 on 2022-03-16 09:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0025_office_office_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='external_id',
            field=models.CharField(default=uuid.uuid4, max_length=50, verbose_name='Office external ID'),
        ),
    ]
