# Generated by Django 3.1 on 2022-04-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0026_auto_20220316_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='office_description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Office Description'),
        ),
    ]
