# Generated by Django 3.1 on 2022-10-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offices', '0027_office_office_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Office order'),
        ),
    ]
