# Generated by Django 3.1 on 2020-09-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20200922_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Număr'),
        ),
    ]
