# Generated by Django 3.1 on 2020-09-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_auto_20200922_0952'),
        ('locations', '0006_auto_20200922_0952'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
