# Generated by Django 3.1 on 2020-09-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0002_auto_20200923_1142'),
        ('locations', '0007_delete_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultipleZonesLocation',
        ),
    ]
