# Generated by Django 3.1 on 2020-11-04 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_auto_20200928_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'verbose_name': 'Street', 'verbose_name_plural': 'Streets'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name': 'Zone', 'verbose_name_plural': 'Zones'},
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, help_text='Country code (two characters) in ISO 3166-1 format', max_length=10),
        ),
        migrations.AlterField(
            model_name='street',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='streets', to='locations.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='street',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.zone', verbose_name='Zone'),
        ),
    ]
