# Generated by Django 3.1 on 2021-05-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_auto_20201104_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='type',
            field=models.CharField(blank=True, choices=[('city', 'City'), ('commune', 'Commune'), ('village', 'Village')], db_index=True, max_length=50),
        ),
    ]
