# Generated by Django 3.1 on 2022-02-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_auto_20210509_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='rex_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rex City ID'),
        ),
        migrations.AddField(
            model_name='region',
            name='rex_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rex Region ID'),
        ),
        migrations.AddField(
            model_name='zone',
            name='rex_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Rex Zone ID'),
        ),
    ]
