# Generated by Django 3.1 on 2022-05-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_auto_20220215_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='id_999',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='City ID 999'),
        ),
        migrations.AddField(
            model_name='region',
            name='id_999',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Region ID 999'),
        ),
        migrations.AddField(
            model_name='zone',
            name='id_999',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Zone ID 999'),
        ),
    ]
