# Generated by Django 3.1 on 2022-10-18 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_auto_20220522_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreetNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, verbose_name='Street Number')),
                ('street', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='number', to='locations.street', verbose_name='Street')),
            ],
            options={
                'verbose_name': 'Street Number',
                'verbose_name_plural': 'Street Numbers',
            },
        ),
    ]
