# Generated by Django 3.1 on 2022-10-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_streetnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='id_999',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Street ID 999'),
        ),
        migrations.AddField(
            model_name='street',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='street',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='streetnumber',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='streetnumber',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
